// Characterisation harness: the stick math of the ADC task, VERBATIM, on the host.
//
// Sources, at dev_refactor 7ea7592 (the split main.cpp, one TU):
//   - main/frag_stick_config.inc:10-33   stick_*_config, stick_apply_cal
//   - main/frag_status_band.inc:154-158  the deadzone constants
//   - main/main.cpp:1433-1447            kIdealAxis and the `static espp::Joystick stick`
//   - main/main.cpp:1481-1601            adc_task_fn from `bool adc_published = false;` to the
//                                        end of the valid-cycle block
//   - main/joystick_cal.hpp:30-39        JoystickAxisCal, JoystickAxis, JoystickCal
//   - main/settings_spec.h:37-38         SETTINGS_STICK_SENSITIVITY_* and SETTINGS_DRIVE_SPEED_*
//                                        (1..10 each, generated by the X-macro)
//   - lvgl/src/core/lv_group.h:26-29     LV_KEY_UP/DOWN/RIGHT/LEFT
//   - rammp_rtps_messages joystick_message.hpp:169-172  rammp::Buttons
//
// The only edits to the copied statements:
//   1. hardware and other-task reads are inputs: adc.get_mv / the twist oversample loop (the
//      three optionals), joystick_cal_take_new, joystick_cal_running, and every atomic, which
//      the harness sets from the vector before the cycle;
//   2. `twist_lowpass` is the identity: the filter reads esp_timer, stays in main, and the
//      vector's twist_mv is its output;
//   3. calls out (joystick_cal_note_raw, lv_subject_set_int, rtps_comms_publish_adc) are fakes
//      that record what they were given;
//   4. the function-local `static bool engaged` and the app_main-local `static espp::Joystick
//      stick` are harness state, so each scenario can start from power-on.
// Keep it that way: this file is the "before" the extraction is measured against.

#include "legacy_adc_cycle.hpp"

#include <algorithm>
#include <array>
#include <atomic>
#include <bit>
#include <cmath>
#include <cstdint>
#include <mutex>
#include <optional>
#include <utility>

#include "joystick.hpp"

namespace stick_test::legacy {
namespace {

// --- main/joystick_cal.hpp:30-39 ---------------------------------------------------------------
struct JoystickAxisCal {
  float min_mv;
  float center_mv;
  float max_mv;
};

enum JoystickAxis { JOY_HORIZONTAL = 0, JOY_VERTICAL = 1, JOY_TWIST = 2 };

using JoystickCal = std::array<JoystickAxisCal, 3>;

// --- main/settings_spec.h:37-38 (X-macro output) -----------------------------------------------
constexpr int SETTINGS_STICK_SENSITIVITY_MIN = 1;
constexpr int SETTINGS_STICK_SENSITIVITY_MAX = 10;
constexpr int SETTINGS_DRIVE_SPEED_MIN = 1;
constexpr int SETTINGS_DRIVE_SPEED_MAX = 10;

// --- lvgl/src/core/lv_group.h:26-29 ------------------------------------------------------------
enum : std::uint32_t {
  LV_KEY_UP = 17,
  LV_KEY_DOWN = 18,
  LV_KEY_RIGHT = 19,
  LV_KEY_LEFT = 20,
};

} // namespace
} // namespace stick_test::legacy

// --- joystick_message.hpp:169-172 --------------------------------------------------------------
namespace rammp {
enum class Buttons : uint32_t {
  NONE = 0x0,
  JOYSTICK = 0x1, /**< the stick's button */
};
} // namespace rammp

namespace stick_test::legacy {
namespace {

// --- main/frag_status_band.inc:154-158 ---------------------------------------------------------
static constexpr float kStickCenterDeadzoneRadius = 0.10f;
static constexpr float kStickRangeDeadzone = 0.05f;
static constexpr float kTwistCenterDeadbandMv = 60.0f;
static constexpr float kTwistRangeDeadbandMv = 40.0f;

// --- main/frag_stick_config.inc:10-33, verbatim --------------------------------------------------
static espp::FloatRangeMapper::Config stick_horizontal_config(const JoystickCal &cal) {
  const JoystickAxisCal &a = cal[JOY_HORIZONTAL];
  return {.center = a.center_mv, .minimum = a.min_mv, .maximum = a.max_mv};
}

static espp::FloatRangeMapper::Config stick_vertical_config(const JoystickCal &cal) {
  const JoystickAxisCal &a = cal[JOY_VERTICAL];
  return {.center = a.center_mv, .minimum = a.min_mv, .maximum = a.max_mv, .invert_output = true};
}

static espp::FloatRangeMapper::Config stick_twist_config(const JoystickCal &cal) {
  const JoystickAxisCal &a = cal[JOY_TWIST];
  return {.center = a.center_mv,
          .center_deadband = kTwistCenterDeadbandMv,
          .minimum = a.min_mv,
          .maximum = a.max_mv,
          .range_deadband = kTwistRangeDeadbandMv};
}

static void stick_apply_cal(espp::Joystick &stick, const JoystickCal &cal) {
  stick.set_calibration(stick_horizontal_config(cal), stick_vertical_config(cal),
                        kStickCenterDeadzoneRadius, kStickRangeDeadzone);
  stick.set_z_calibration(stick_twist_config(cal));
}

// --- the calibrations the vectors name ---------------------------------------------------------
// main.cpp:1433-1434
static constexpr JoystickAxisCal kIdealAxis{
    .min_mv = 0.0f, .center_mv = 1650.0f, .max_mv = 3300.0f};
constexpr JoystickCal CAL_IDEAL_MV{kIdealAxis, kIdealAxis, kIdealAxis};
// board 2, as measured by CALIBRATE (refactor brief, step 11)
constexpr JoystickCal CAL_BOARD2_MV{JoystickAxisCal{11.0f, 1507.0f, 2971.0f},
                                    JoystickAxisCal{6.0f, 1510.0f, 2962.0f},
                                    JoystickAxisCal{10.0f, 1477.0f, 2960.0f}};

std::optional<JoystickCal> cal_of(std::uint8_t id) {
  switch (id) {
  case CAL_IDEAL:
    return CAL_IDEAL_MV;
  case CAL_BOARD2:
    return CAL_BOARD2_MV;
  default:
    return std::nullopt;
  }
}

// --- harness state: the statics of the original ------------------------------------------------
std::optional<espp::Joystick> g_stick;
bool g_engaged = false; // was `static bool engaged = false;` in the key block

std::atomic<bool> stick_swap{false};
std::atomic<bool> stick_invert_x{false};
std::atomic<bool> stick_invert_y{false};
std::atomic<int> stick_sensitivity{SETTINGS_STICK_SENSITIVITY_MAX - 1};
std::atomic<int> drive_speed{SETTINGS_DRIVE_SPEED_MAX};
std::atomic<bool> stick_drives{false};
std::atomic<bool> joy_button_pressed{false};
std::atomic<uint32_t> joy_key{0};
std::atomic<uint32_t> remote_key{0};
std::atomic<uint32_t> joy_flick{0};

std::recursive_mutex lvgl_mutex;

// --- fakes for the calls in and out ------------------------------------------------------------
std::optional<JoystickCal> g_new_cal;
bool g_calibrating = false;
StickOutputs g_out{};

std::optional<JoystickCal> joystick_cal_take_new() {
  return std::exchange(g_new_cal, std::nullopt);
}
bool joystick_cal_running() { return g_calibrating; }
void joystick_cal_note_raw(float, float, float) {}

struct IdentityFilter {
  float operator()(float v) const { return v; }
};
const IdentityFilter twist_lowpass{};

struct lv_subject_t {
  std::int32_t *slot;
};
lv_subject_t adc_x_subject{&g_out.bar_x};
lv_subject_t adc_y_subject{&g_out.bar_y};
lv_subject_t adc_twist_subject{&g_out.bar_twist};
void lv_subject_set_int(lv_subject_t *subject, std::int32_t value) {
  *subject->slot = value;
  g_out.bars_set = true;
}

bool rtps_comms_publish_adc(float x, float y, float twist, rammp::Buttons buttons) {
  g_out.published = true;
  g_out.cmd_x = std::bit_cast<std::uint32_t>(x);
  g_out.cmd_y = std::bit_cast<std::uint32_t>(y);
  g_out.cmd_twist = std::bit_cast<std::uint32_t>(twist);
  g_out.buttons = static_cast<std::uint32_t>(buttons);
  return true;
}

// The body of adc_task_fn after its reads (main.cpp:1481-1601), verbatim apart from the edits
// listed at the top. Returns adc_published.
bool adc_cycle_body(std::optional<float> vert_mv, std::optional<float> horiz_mv,
                    std::optional<float> twist_mv) {
  espp::Joystick &stick = *g_stick; // was app_main's `static espp::Joystick stick`
  bool adc_published = false;
  if (vert_mv && horiz_mv && twist_mv) {
    // A calibration run just finished: switch to it here, between two
    // samples, on the task that owns the stick.
    if (auto cal = joystick_cal_take_new()) {
      stick_apply_cal(stick, *cal);
    }
    const float twist_smoothed = twist_lowpass(*twist_mv);
    joystick_cal_note_raw(*horiz_mv, *vert_mv, twist_smoothed);
    // While a calibration run owns the stick nothing downstream may act on
    // it: the user is being told to push it to every end in turn.
    const bool calibrating = joystick_cal_running();

    // raw mV -> calibrated [-1,1] per axis: circular deadzone on the X/Y
    // gimbal, twist mapped independently by its own range mapper. X is the
    // horizontal channel, Y the vertical one (inverted, see "Joystick
    // mapping").
    stick.update(*horiz_mv, *vert_mv, twist_smoothed);
    // The stick as mounted: Settings can swap its axes and mirror either
    // one. Applied here, once, so the bars, the UI keys and the MCB all get
    // the same stick. Swap first, then mirror, so "mirror left/right" always
    // means the direction the user pushes, whatever the swap did.
    float stick_x = stick.x();
    float stick_y = stick.y();
    if (stick_swap.load()) {
      std::swap(stick_x, stick_y);
    }
    if (stick_invert_x.load()) {
      stick_x = -stick_x;
    }
    if (stick_invert_y.load()) {
      stick_y = -stick_y;
    }

    // Analog -> keypad level. (main.cpp:1514-1530: the threshold comment)
    const int level = std::clamp<int>(stick_sensitivity.load(), SETTINGS_STICK_SENSITIVITY_MIN,
                                      SETTINGS_STICK_SENSITIVITY_MAX);
    const float kKeyEngage = 0.30f - (level - 1) * (0.29f / 9.0f);
    const float kKeyRelease = kKeyEngage * 0.5f;
    {
      bool &engaged = g_engaged; // was `static bool engaged = false;`
      const float x = stick_x;
      const float y = stick_y;
      const float mag = std::max(std::abs(x), std::abs(y));
      if (calibrating) {
        engaged = false; // "hold LEFT" must not page the menus or exit
      } else if (mag > kKeyEngage) {
        engaged = true;
      } else if (mag < kKeyRelease) {
        engaged = false;
      }
      const uint32_t was = joy_key.load();
      if (remote_key.load() != 0) {
        joy_key.store(remote_key.load());
      } else if (!engaged) {
        joy_key.store(0);
      } else if (std::abs(x) >= std::abs(y)) {
        joy_key.store(x > 0 ? LV_KEY_RIGHT : LV_KEY_LEFT);
      } else {
        // +Y is up after the vertical axis's inversion, and up the list is prev
        joy_key.store(y > 0 ? LV_KEY_UP : LV_KEY_DOWN);
      }
      // A fresh engage (or a re-aim) is latched for the keypad; see joy_flick.
      if (const uint32_t now = joy_key.load(); now != 0 && now != was) {
        joy_flick.store(now);
      }
    }
    {
      // (main.cpp:1561-1566: why the LVGL lock is tried, not waited for)
      std::unique_lock<std::recursive_mutex> lock(lvgl_mutex, std::try_to_lock);
      if (lock.owns_lock()) {
        lv_subject_set_int(&adc_x_subject, static_cast<int32_t>(stick_x * 100.0f));
        lv_subject_set_int(&adc_y_subject, static_cast<int32_t>(stick_y * 100.0f));
        lv_subject_set_int(&adc_twist_subject, static_cast<int32_t>(stick.z() * 100.0f));
      }
    }

    // (main.cpp:1575-1591: the gate and the speed scaling)
    const float speed =
        static_cast<float>(std::clamp<int>(drive_speed.load(), SETTINGS_DRIVE_SPEED_MIN,
                                           SETTINGS_DRIVE_SPEED_MAX)) /
        static_cast<float>(SETTINGS_DRIVE_SPEED_MAX);
    const float scale = calibrating || !stick_drives.load() ? 0.0f : speed;
    adc_published = rtps_comms_publish_adc(stick_x * scale, stick_y * scale, stick.z() * scale,
                                           joy_button_pressed.load() ? rammp::Buttons::JOYSTICK
                                                                     : rammp::Buttons::NONE);
  }
  return adc_published;
}

} // namespace

void reset(CalId cal) {
  // main.cpp:1435-1447: the joystick is built on the calibration joystick_cal_load returned
  const JoystickCal joystick_cal = *cal_of(cal);
  g_stick.reset();
  g_stick.emplace(espp::Joystick::Config{.x_calibration = stick_horizontal_config(joystick_cal),
                                         .y_calibration = stick_vertical_config(joystick_cal),
                                         .z_calibration = stick_twist_config(joystick_cal),
                                         .type = espp::Joystick::Type::CIRCULAR,
                                         .center_deadzone_radius = kStickCenterDeadzoneRadius,
                                         .range_deadzone = kStickRangeDeadzone,
                                         .log_level = espp::Logger::Verbosity::WARN});
  g_engaged = false;
  g_new_cal.reset();
  joy_key.store(0);
  remote_key.store(0);
  joy_flick.store(0);
}

StickOutputs cycle(const StickVector &v) {
  if (v.reset || !g_stick) {
    reset(static_cast<CalId>(v.power_on_cal));
  }
  g_out = StickOutputs{};
  if (v.new_cal != CAL_NONE) {
    g_new_cal = cal_of(v.new_cal); // pending until a valid cycle takes it, as in joystick_cal
  }
  g_calibrating = v.calibrating;
  stick_swap.store(v.swap);
  stick_invert_x.store(v.invert_x);
  stick_invert_y.store(v.invert_y);
  stick_sensitivity.store(v.sensitivity);
  remote_key.store(v.remote_key);
  drive_speed.store(v.drive_speed);
  stick_drives.store(v.drives);
  joy_button_pressed.store(v.button);
  joy_flick.store(0); // the keypad read consumed the last flick (main.cpp:730)

  const std::optional<float> vert = v.vert_ok ? std::optional<float>{v.vert_mv} : std::nullopt;
  const std::optional<float> horiz = v.horiz_ok ? std::optional<float>{v.horiz_mv} : std::nullopt;
  const std::optional<float> twist = v.twist_ok ? std::optional<float>{v.twist_mv} : std::nullopt;
  (void)adc_cycle_body(vert, horiz, twist); // its result is g_out.published (the fake's call)
  g_out.joy_key = joy_key.load();
  g_out.joy_flick = joy_flick.load();
  return g_out;
}

} // namespace stick_test::legacy
