#pragma once
// Hand-written inputs modelled on GitHub's REST API answer to
// GET /repos/{owner}/{repo}/releases (docs.github.com, "List releases", API 2022-11-28):
// an array of release objects with tag_name, name, draft, prerelease, published_at, body and
// assets[] (name, size, digest "sha256:<hex>", browser_download_url, ...). The firmware's own
// asset is rammp-hmi-p4.bin (main/github_ota.cpp:41). Not recorded from the network: no
// secrets, nothing that changes.

#include <string_view>

namespace ota_test {

inline constexpr std::string_view kSha1 =
    "3f9a0c6e1b2d4f5a6b7c8d9e0f1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c";
inline constexpr std::string_view kSha2 =
    "aa00bb11cc22dd33ee44ff5566778899aabbccddeeff00112233445566778899";

// Five releases, newest first: a release with the image and its digest, a pre-release whose
// image has no digest, a draft (left out), an old release without the image, and one with an
// empty tag (left out).
inline constexpr std::string_view kReleasesRealistic = R"json([
  {
    "url": "https://api.github.com/repos/rammp-org/pace-hmi-fw/releases/250000001",
    "html_url": "https://github.com/rammp-org/pace-hmi-fw/releases/tag/v4.1.0",
    "id": 250000001,
    "author": {"login": "github-actions[bot]", "id": 41898282, "type": "Bot"},
    "node_id": "RE_kwDOAAAAAA4O5ZVh",
    "tag_name": "v4.1.0",
    "target_commitish": "main",
    "name": "v4.1.0",
    "draft": false,
    "immutable": false,
    "prerelease": false,
    "created_at": "2026-09-30T18:02:11Z",
    "updated_at": "2026-09-30T18:09:40Z",
    "published_at": "2026-09-30T18:09:39Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/rammp-org/pace-hmi-fw/releases/assets/300000001",
        "id": 300000001,
        "node_id": "RA_kwDOAAAAAA4R3ZVh",
        "name": "bootloader.bin",
        "label": "",
        "content_type": "application/octet-stream",
        "state": "uploaded",
        "size": 24576,
        "digest": "sha256:0000000000000000000000000000000000000000000000000000000000000000",
        "download_count": 3,
        "created_at": "2026-09-30T18:09:20Z",
        "updated_at": "2026-09-30T18:09:21Z",
        "browser_download_url": "https://github.com/rammp-org/pace-hmi-fw/releases/download/v4.1.0/bootloader.bin"
      },
      {
        "url": "https://api.github.com/repos/rammp-org/pace-hmi-fw/releases/assets/300000002",
        "id": 300000002,
        "name": "rammp-hmi-p4.bin",
        "label": "",
        "content_type": "application/octet-stream",
        "state": "uploaded",
        "size": 3891200,
        "digest": "sha256:3f9a0c6e1b2d4f5a6b7c8d9e0f1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c",
        "download_count": 12,
        "created_at": "2026-09-30T18:09:22Z",
        "updated_at": "2026-09-30T18:09:30Z",
        "browser_download_url": "https://github.com/rammp-org/pace-hmi-fw/releases/download/v4.1.0/rammp-hmi-p4.bin"
      },
      {
        "name": "partition-table.bin",
        "size": 3072,
        "browser_download_url": "https://github.com/rammp-org/pace-hmi-fw/releases/download/v4.1.0/partition-table.bin"
      }
    ],
    "tarball_url": "https://api.github.com/repos/rammp-org/pace-hmi-fw/tarball/v4.1.0",
    "zipball_url": "https://api.github.com/repos/rammp-org/pace-hmi-fw/zipball/v4.1.0",
    "body": "## What's new\r\n\r\n* **Firmware update** from GitHub releases — with rollback.\r\n* `About` shows the image's SHA‑256.\r\n\r\n\r\n\r\nSee docs → OTA. It’s “safe”… 🚀\r\n\r\n### ESP-IDF Size Report\r\n| Total | 3.8 MB |\r\n"
  },
  {
    "tag_name": "v4.1.0-rc1",
    "name": "v4.1.0 release candidate",
    "draft": false,
    "prerelease": true,
    "published_at": "2026-09-28T09:00:00Z",
    "assets": [
      {
        "name": "rammp-hmi-p4.bin",
        "size": 3890000,
        "browser_download_url": "https://github.com/rammp-org/pace-hmi-fw/releases/download/v4.1.0-rc1/rammp-hmi-p4.bin"
      }
    ],
    "body": "Release candidate: test on the bench first.<!-- generated by CI: 1234 -->\nhidden"
  },
  {
    "tag_name": "v4.2.0",
    "name": "next (draft)",
    "draft": true,
    "prerelease": false,
    "published_at": null,
    "assets": [
      {
        "name": "rammp-hmi-p4.bin",
        "size": 3900000,
        "digest": "sha256:aa00bb11cc22dd33ee44ff5566778899aabbccddeeff00112233445566778899",
        "browser_download_url": "https://github.com/rammp-org/pace-hmi-fw/releases/download/v4.2.0/rammp-hmi-p4.bin"
      }
    ],
    "body": "draft"
  },
  {
    "tag_name": "v3.9.0",
    "name": "v3.9.0",
    "draft": false,
    "prerelease": false,
    "published_at": "2026-06-01T12:00:00Z",
    "assets": [
      {"name": "hmi.bin", "size": 3500000, "browser_download_url": "https://github.com/rammp-org/pace-hmi-fw/releases/download/v3.9.0/hmi.bin"}
    ],
    "body": null
  },
  {
    "tag_name": "",
    "draft": false,
    "prerelease": false,
    "assets": []
  }
])json";

// One release with the image listed twice: the second has no digest. Today the url and size
// come from the second and the digest stays from the first (github_ota.cpp:229-241).
inline constexpr std::string_view kReleasesDuplicateAsset = R"json([
  {"tag_name": "v5.0.0", "prerelease": false, "published_at": "2026-10-01T00:00:00Z",
   "assets": [
     {"name": "rammp-hmi-p4.bin", "size": 100,
      "digest": "sha256:3f9a0c6e1b2d4f5a6b7c8d9e0f1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c",
      "browser_download_url": "https://github.com/a/first.bin"},
     {"name": "rammp-hmi-p4.bin", "size": 200, "digest": "md5:abc",
      "browser_download_url": "https://example.com/second.bin"}
   ],
   "body": "two"}
])json";

// fwinfo.txt as scripts/fw_verify.py and fw_info_record_release write it (fw_info.hpp:17).
inline constexpr std::string_view kFwInfoRealistic =
    "# <sha256>  <tag>  <release|prerelease>  <checked>\n"
    "\n"
    "aa00bb11cc22dd33ee44ff5566778899aabbccddeeff00112233445566778899  v4.0.0  release  "
    "2026-09-01T10:00:00Z\n"
    "3f9a0c6e1b2d4f5a6b7c8d9e0f1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c  v4.1.0-rc1  prerelease  "
    "unknown\r\n"
    "1111111111111111111111111111111111111111111111111111111111111111  v3.0.0  release\n";

} // namespace ota_test
