#!/usr/bin/env python3
"""The self-test check table as rows, for the parity app (TS-UNIT-04, CS-TYP-03).

Three views of main/selftest_spec.hpp must agree, row for row and in order:
  - golden_rows.json: the table as it was characterised (written once, by `golden`);
  - the host scripts' parse of the header (rammp_rtps.parse_selftest_spec, which
    rtps_selftest.py uses);
  - the firmware's own C++ table (compared in test_selftest_spec.cpp).

usage:
  rows.py golden --repo REPO                      write golden_rows.json from the script parse
  rows.py emit --repo REPO --source golden|script --out FILE
                                                  write the rows as C++ initialisers
"""

from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GOLDEN = os.path.join(HERE, "golden_rows.json")
INT32_MIN = -(2 ** 31)
INT32_MAX = 2 ** 31 - 1
FIELDS = ("order", "id", "name", "unit", "lo", "hi", "need", "why")


def script_rows(repo: str) -> list[dict]:
    """The header as the host scripts read it."""
    sys.path.insert(0, os.path.join(repo, "scripts"))
    import rammp_rtps  # noqa: E402  (path setup must run first)

    with open(rammp_rtps.SELFTEST_SPEC_PATH, encoding="utf-8") as handle:
        rows = rammp_rtps.parse_selftest_spec(handle.read())
    if not rows:
        sys.exit(f"rows.py: {rammp_rtps.SELFTEST_SPEC_PATH} parsed to nothing")
    return [{"order": i, "id": r.id, "name": r.name, "unit": r.unit, "lo": r.lo, "hi": r.hi,
             "need": r.need, "why": r.desc} for i, r in enumerate(rows)]


def golden_rows() -> list[dict]:
    with open(GOLDEN, encoding="utf-8") as handle:
        rows = json.load(handle)
    for i, row in enumerate(rows):
        if tuple(row) != FIELDS or row["order"] != i:
            sys.exit(f"rows.py: {GOLDEN}: row {i} is malformed")
    return rows


def c_string(text: str) -> str:
    if not all(" " <= ch <= "~" for ch in text):
        sys.exit(f"rows.py: non-printable or non-ASCII text in the table: {text!r}")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_limit(value: int) -> str:
    return "INT32_MIN" if value == INT32_MIN else "INT32_MAX" if value == INT32_MAX else str(value)


def emit(rows: list[dict], out: str) -> None:
    lines = ["// generated by tests/host/selftest_spec_parity/rows.py; do not edit"]
    for r in rows:
        lines.append(f"Row{{{c_string(r['id'])}, {c_string(r['name'])}, {c_string(r['unit'])}, "
                     f"{c_limit(r['lo'])}, {c_limit(r['hi'])}, {c_string(r['need'])}, "
                     f"{c_string(r['why'])}}},")
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("command", choices=("golden", "emit"))
    ap.add_argument("--repo", default=os.path.abspath(os.path.join(HERE, "..", "..", "..")))
    ap.add_argument("--source", choices=("golden", "script"))
    ap.add_argument("--out")
    args = ap.parse_args()
    if args.command == "golden":
        rows = [json.dumps(row) for row in script_rows(args.repo)]  # one row per line
        with open(GOLDEN, "w", encoding="utf-8", newline="\n") as handle:
            handle.write("[\n" + ",\n".join(rows) + "\n]\n")
        return 0
    if not args.source or not args.out:
        ap.error("emit needs --source and --out")
    emit(golden_rows() if args.source == "golden" else script_rows(args.repo), args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
