#pragma once
// GOLDEN tables: what the cursor walk and the PIN entry did before they moved out of main/
// (dev_refactor ad152dd), recorded from the verbatim copies in legacy_ui.cpp. Frozen: a failing
// row is a behaviour change in the code under test, never a reason to edit this file (CORE
// never-list).

#include "shapes.hpp"

namespace models_test {

/// One arrow key from one cursor on one firmware grid. The cursor is set to (row, col) with
/// focus on that cell (or elsewhere, for a hole or a cell outside the shape).
struct GridGolden {
  GridId grid;
  int row;
  int col;
  Key key;
  Move move;  ///< MOVED, or the edge handler that ran instead
  int to_row; ///< the cursor afterwards
  int to_col;
  bool focused; ///< focus moved to the cell at (to_row, to_col)
};

/// One key of one PIN_SEQUENCES entry, and what the pad showed after it.
struct PinGolden {
  int sequence; ///< index into PIN_SEQUENCES
  char key;     ///< R (visit), B (backspace) or a digit
  int dots;     ///< the dots lit afterwards (rd_pin_len_subject)
  bool wrong;   ///< the line reads "Incorrect PIN - try again" (else the prompt)
  int opened;   ///< actuator pages opened since the visit (setting_page_open)
  int typed;    ///< the dots the key first wrote, -1 if it wrote none (an R row: -1)
};

using G = GridId;
using K = Key;
using M = Move;

inline constexpr GridGolden GRID_GOLDEN[] = {
    {G::SEAT_FUNCTIONS, 0, 0, K::UP, M::MOVED, 0, 0, true},
    {G::SEAT_FUNCTIONS, 0, 0, K::DOWN, M::MOVED, 1, 0, true},
    {G::SEAT_FUNCTIONS, 0, 0, K::LEFT, M::MOVED, 0, 0, true},
    {G::SEAT_FUNCTIONS, 0, 0, K::RIGHT, M::MOVED, 0, 1, true},
    {G::SEAT_FUNCTIONS, 0, 1, K::UP, M::MOVED, 0, 1, true},
    {G::SEAT_FUNCTIONS, 0, 1, K::DOWN, M::MOVED, 1, 1, true},
    {G::SEAT_FUNCTIONS, 0, 1, K::LEFT, M::MOVED, 0, 0, true},
    {G::SEAT_FUNCTIONS, 0, 1, K::RIGHT, M::MOVED, 0, 1, true},
    {G::SEAT_FUNCTIONS, 0, 2, K::UP, M::MOVED, 0, 1, true},
    {G::SEAT_FUNCTIONS, 0, 2, K::DOWN, M::MOVED, 1, 1, true},
    {G::SEAT_FUNCTIONS, 0, 2, K::LEFT, M::MOVED, 0, 1, true},
    {G::SEAT_FUNCTIONS, 0, 2, K::RIGHT, M::MOVED, 0, 1, true},
    {G::SEAT_FUNCTIONS, 1, 0, K::UP, M::MOVED, 0, 0, true},
    {G::SEAT_FUNCTIONS, 1, 0, K::DOWN, M::MOVED, 2, 0, true},
    {G::SEAT_FUNCTIONS, 1, 0, K::LEFT, M::MOVED, 1, 0, true},
    {G::SEAT_FUNCTIONS, 1, 0, K::RIGHT, M::MOVED, 1, 1, true},
    {G::SEAT_FUNCTIONS, 1, 1, K::UP, M::MOVED, 0, 1, true},
    {G::SEAT_FUNCTIONS, 1, 1, K::DOWN, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 1, 1, K::LEFT, M::MOVED, 1, 0, true},
    {G::SEAT_FUNCTIONS, 1, 1, K::RIGHT, M::MOVED, 1, 1, true},
    {G::SEAT_FUNCTIONS, 1, 2, K::UP, M::MOVED, 0, 1, true},
    {G::SEAT_FUNCTIONS, 1, 2, K::DOWN, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 1, 2, K::LEFT, M::MOVED, 1, 1, true},
    {G::SEAT_FUNCTIONS, 1, 2, K::RIGHT, M::MOVED, 1, 1, true},
    {G::SEAT_FUNCTIONS, 2, 0, K::UP, M::MOVED, 1, 0, true},
    {G::SEAT_FUNCTIONS, 2, 0, K::DOWN, M::OFF_BOTTOM, 2, 0, false},
    {G::SEAT_FUNCTIONS, 2, 0, K::LEFT, M::MOVED, 2, 0, true},
    {G::SEAT_FUNCTIONS, 2, 0, K::RIGHT, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 2, 1, K::UP, M::MOVED, 1, 1, true},
    {G::SEAT_FUNCTIONS, 2, 1, K::DOWN, M::OFF_BOTTOM, 2, 1, false},
    {G::SEAT_FUNCTIONS, 2, 1, K::LEFT, M::MOVED, 2, 0, true},
    {G::SEAT_FUNCTIONS, 2, 1, K::RIGHT, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 2, 2, K::UP, M::MOVED, 1, 1, true},
    {G::SEAT_FUNCTIONS, 2, 2, K::DOWN, M::OFF_BOTTOM, 2, 2, false},
    {G::SEAT_FUNCTIONS, 2, 2, K::LEFT, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 2, 2, K::RIGHT, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 3, 0, K::UP, M::MOVED, 2, 0, true},
    {G::SEAT_FUNCTIONS, 3, 0, K::DOWN, M::OFF_BOTTOM, 3, 0, false},
    {G::SEAT_FUNCTIONS, 3, 0, K::LEFT, M::MOVED, 2, 0, true},
    {G::SEAT_FUNCTIONS, 3, 0, K::RIGHT, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 3, 1, K::UP, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 3, 1, K::DOWN, M::OFF_BOTTOM, 3, 1, false},
    {G::SEAT_FUNCTIONS, 3, 1, K::LEFT, M::MOVED, 2, 0, true},
    {G::SEAT_FUNCTIONS, 3, 1, K::RIGHT, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 3, 2, K::UP, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 3, 2, K::DOWN, M::OFF_BOTTOM, 3, 2, false},
    {G::SEAT_FUNCTIONS, 3, 2, K::LEFT, M::MOVED, 2, 1, true},
    {G::SEAT_FUNCTIONS, 3, 2, K::RIGHT, M::MOVED, 2, 1, true},
    {G::SEAT_ADJUST, 0, 0, K::UP, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 0, 0, K::DOWN, M::MOVED, 1, 0, true},
    {G::SEAT_ADJUST, 0, 0, K::LEFT, M::OFF_LEFT, 0, 0, false},
    {G::SEAT_ADJUST, 0, 0, K::RIGHT, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 0, 1, K::UP, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 0, 1, K::DOWN, M::MOVED, 1, 1, true},
    {G::SEAT_ADJUST, 0, 1, K::LEFT, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 0, 1, K::RIGHT, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 0, 2, K::UP, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 0, 2, K::DOWN, M::MOVED, 1, 1, true},
    {G::SEAT_ADJUST, 0, 2, K::LEFT, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 0, 2, K::RIGHT, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 1, 0, K::UP, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 1, 0, K::DOWN, M::MOVED, 2, 0, true},
    {G::SEAT_ADJUST, 1, 0, K::LEFT, M::OFF_LEFT, 1, 0, false},
    {G::SEAT_ADJUST, 1, 0, K::RIGHT, M::MOVED, 1, 1, true},
    {G::SEAT_ADJUST, 1, 1, K::UP, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 1, 1, K::DOWN, M::MOVED, 2, 1, true},
    {G::SEAT_ADJUST, 1, 1, K::LEFT, M::MOVED, 1, 0, true},
    {G::SEAT_ADJUST, 1, 1, K::RIGHT, M::MOVED, 1, 1, true},
    {G::SEAT_ADJUST, 1, 2, K::UP, M::MOVED, 0, 0, true},
    {G::SEAT_ADJUST, 1, 2, K::DOWN, M::MOVED, 2, 2, true},
    {G::SEAT_ADJUST, 1, 2, K::LEFT, M::MOVED, 1, 1, true},
    {G::SEAT_ADJUST, 1, 2, K::RIGHT, M::MOVED, 1, 1, true},
    {G::SEAT_ADJUST, 2, 0, K::UP, M::MOVED, 1, 0, true},
    {G::SEAT_ADJUST, 2, 0, K::DOWN, M::OFF_BOTTOM, 2, 0, false},
    {G::SEAT_ADJUST, 2, 0, K::LEFT, M::OFF_LEFT, 2, 0, false},
    {G::SEAT_ADJUST, 2, 0, K::RIGHT, M::MOVED, 2, 1, true},
    {G::SEAT_ADJUST, 2, 1, K::UP, M::MOVED, 1, 1, true},
    {G::SEAT_ADJUST, 2, 1, K::DOWN, M::OFF_BOTTOM, 2, 1, false},
    {G::SEAT_ADJUST, 2, 1, K::LEFT, M::MOVED, 2, 0, true},
    {G::SEAT_ADJUST, 2, 1, K::RIGHT, M::MOVED, 2, 2, true},
    {G::SEAT_ADJUST, 2, 2, K::UP, M::MOVED, 1, 1, true},
    {G::SEAT_ADJUST, 2, 2, K::DOWN, M::OFF_BOTTOM, 2, 2, false},
    {G::SEAT_ADJUST, 2, 2, K::LEFT, M::MOVED, 2, 1, true},
    {G::SEAT_ADJUST, 2, 2, K::RIGHT, M::MOVED, 2, 2, true},
    {G::SEAT_ADJUST, 3, 0, K::UP, M::MOVED, 2, 0, true},
    {G::SEAT_ADJUST, 3, 0, K::DOWN, M::OFF_BOTTOM, 3, 0, false},
    {G::SEAT_ADJUST, 3, 0, K::LEFT, M::OFF_LEFT, 3, 0, false},
    {G::SEAT_ADJUST, 3, 0, K::RIGHT, M::MOVED, 2, 1, true},
    {G::SEAT_ADJUST, 3, 1, K::UP, M::MOVED, 2, 1, true},
    {G::SEAT_ADJUST, 3, 1, K::DOWN, M::OFF_BOTTOM, 3, 1, false},
    {G::SEAT_ADJUST, 3, 1, K::LEFT, M::MOVED, 2, 0, true},
    {G::SEAT_ADJUST, 3, 1, K::RIGHT, M::MOVED, 2, 2, true},
    {G::SEAT_ADJUST, 3, 2, K::UP, M::MOVED, 2, 2, true},
    {G::SEAT_ADJUST, 3, 2, K::DOWN, M::OFF_BOTTOM, 3, 2, false},
    {G::SEAT_ADJUST, 3, 2, K::LEFT, M::MOVED, 2, 1, true},
    {G::SEAT_ADJUST, 3, 2, K::RIGHT, M::MOVED, 2, 2, true},
    {G::PIN_PAD, 0, 0, K::UP, M::MOVED, 0, 0, true},
    {G::PIN_PAD, 0, 0, K::DOWN, M::MOVED, 1, 0, true},
    {G::PIN_PAD, 0, 0, K::LEFT, M::MOVED, 0, 0, true},
    {G::PIN_PAD, 0, 0, K::RIGHT, M::MOVED, 0, 1, true},
    {G::PIN_PAD, 0, 1, K::UP, M::MOVED, 0, 1, true},
    {G::PIN_PAD, 0, 1, K::DOWN, M::MOVED, 1, 1, true},
    {G::PIN_PAD, 0, 1, K::LEFT, M::MOVED, 0, 0, true},
    {G::PIN_PAD, 0, 1, K::RIGHT, M::MOVED, 0, 2, true},
    {G::PIN_PAD, 0, 2, K::UP, M::MOVED, 0, 2, true},
    {G::PIN_PAD, 0, 2, K::DOWN, M::MOVED, 1, 2, true},
    {G::PIN_PAD, 0, 2, K::LEFT, M::MOVED, 0, 1, true},
    {G::PIN_PAD, 0, 2, K::RIGHT, M::MOVED, 0, 2, true},
    {G::PIN_PAD, 1, 0, K::UP, M::MOVED, 0, 0, true},
    {G::PIN_PAD, 1, 0, K::DOWN, M::MOVED, 2, 0, true},
    {G::PIN_PAD, 1, 0, K::LEFT, M::MOVED, 1, 0, true},
    {G::PIN_PAD, 1, 0, K::RIGHT, M::MOVED, 1, 1, true},
    {G::PIN_PAD, 1, 1, K::UP, M::MOVED, 0, 1, true},
    {G::PIN_PAD, 1, 1, K::DOWN, M::MOVED, 2, 1, true},
    {G::PIN_PAD, 1, 1, K::LEFT, M::MOVED, 1, 0, true},
    {G::PIN_PAD, 1, 1, K::RIGHT, M::MOVED, 1, 2, true},
    {G::PIN_PAD, 1, 2, K::UP, M::MOVED, 0, 2, true},
    {G::PIN_PAD, 1, 2, K::DOWN, M::MOVED, 2, 2, true},
    {G::PIN_PAD, 1, 2, K::LEFT, M::MOVED, 1, 1, true},
    {G::PIN_PAD, 1, 2, K::RIGHT, M::MOVED, 1, 2, true},
    {G::PIN_PAD, 2, 0, K::UP, M::MOVED, 1, 0, true},
    {G::PIN_PAD, 2, 0, K::DOWN, M::MOVED, 3, 1, true},
    {G::PIN_PAD, 2, 0, K::LEFT, M::MOVED, 2, 0, true},
    {G::PIN_PAD, 2, 0, K::RIGHT, M::MOVED, 2, 1, true},
    {G::PIN_PAD, 2, 1, K::UP, M::MOVED, 1, 1, true},
    {G::PIN_PAD, 2, 1, K::DOWN, M::MOVED, 3, 1, true},
    {G::PIN_PAD, 2, 1, K::LEFT, M::MOVED, 2, 0, true},
    {G::PIN_PAD, 2, 1, K::RIGHT, M::MOVED, 2, 2, true},
    {G::PIN_PAD, 2, 2, K::UP, M::MOVED, 1, 2, true},
    {G::PIN_PAD, 2, 2, K::DOWN, M::MOVED, 3, 2, true},
    {G::PIN_PAD, 2, 2, K::LEFT, M::MOVED, 2, 1, true},
    {G::PIN_PAD, 2, 2, K::RIGHT, M::MOVED, 2, 2, true},
    {G::PIN_PAD, 3, 0, K::UP, M::MOVED, 2, 0, true},
    {G::PIN_PAD, 3, 0, K::DOWN, M::OFF_BOTTOM, 3, 0, false},
    {G::PIN_PAD, 3, 0, K::LEFT, M::MOVED, 3, 1, true},
    {G::PIN_PAD, 3, 0, K::RIGHT, M::MOVED, 3, 1, true},
    {G::PIN_PAD, 3, 1, K::UP, M::MOVED, 2, 1, true},
    {G::PIN_PAD, 3, 1, K::DOWN, M::OFF_BOTTOM, 3, 1, false},
    {G::PIN_PAD, 3, 1, K::LEFT, M::MOVED, 3, 1, true},
    {G::PIN_PAD, 3, 1, K::RIGHT, M::MOVED, 3, 2, true},
    {G::PIN_PAD, 3, 2, K::UP, M::MOVED, 2, 2, true},
    {G::PIN_PAD, 3, 2, K::DOWN, M::OFF_BOTTOM, 3, 2, false},
    {G::PIN_PAD, 3, 2, K::LEFT, M::MOVED, 3, 1, true},
    {G::PIN_PAD, 3, 2, K::RIGHT, M::MOVED, 3, 2, true},
};

inline constexpr PinGolden PIN_GOLDEN[] = {
    {0, 'R', 0, false, 0, -1},  {0, '1', 1, false, 0, 1},   {0, '2', 2, false, 0, 2},
    {0, '3', 3, false, 0, 3},   {0, '4', 0, false, 1, 4},   {1, 'R', 0, false, 0, -1},
    {1, '1', 1, false, 0, 1},   {1, '2', 2, false, 0, 2},   {1, '3', 3, false, 0, 3},
    {1, '5', 0, true, 0, 4},    {2, 'R', 0, false, 0, -1},  {2, '1', 1, false, 0, 1},
    {2, '2', 2, false, 0, 2},   {2, '3', 3, false, 0, 3},   {2, '5', 0, true, 0, 4},
    {2, '1', 1, false, 0, 1},   {2, '2', 2, false, 0, 2},   {2, '3', 3, false, 0, 3},
    {2, '4', 0, false, 1, 4},   {3, 'R', 0, false, 0, -1},  {3, 'B', 0, false, 0, -1},
    {3, 'B', 0, false, 0, -1},  {4, 'R', 0, false, 0, -1},  {4, '1', 1, false, 0, 1},
    {4, '2', 2, false, 0, 2},   {4, 'B', 1, false, 0, 1},   {4, 'B', 0, false, 0, 0},
    {4, 'B', 0, false, 0, -1},  {4, '1', 1, false, 0, 1},   {4, '2', 2, false, 0, 2},
    {4, '3', 3, false, 0, 3},   {4, '4', 0, false, 1, 4},   {5, 'R', 0, false, 0, -1},
    {5, '0', 1, false, 0, 1},   {5, '0', 2, false, 0, 2},   {5, '0', 3, false, 0, 3},
    {5, '0', 0, true, 0, 4},    {5, '5', 1, false, 0, 1},   {6, 'R', 0, false, 0, -1},
    {6, '1', 1, false, 0, 1},   {6, '2', 2, false, 0, 2},   {6, '3', 3, false, 0, 3},
    {6, '4', 0, false, 1, 4},   {6, '5', 1, false, 1, 1},   {7, 'R', 0, false, 0, -1},
    {7, '1', 1, false, 0, 1},   {7, '2', 2, false, 0, 2},   {7, '3', 3, false, 0, 3},
    {7, 'B', 2, false, 0, 2},   {7, '3', 3, false, 0, 3},   {7, '4', 0, false, 1, 4},
    {8, 'R', 0, false, 0, -1},  {8, '9', 1, false, 0, 1},   {8, '9', 2, false, 0, 2},
    {8, '9', 3, false, 0, 3},   {8, '9', 0, true, 0, 4},    {8, 'B', 0, true, 0, -1},
    {8, '1', 1, false, 0, 1},   {9, 'R', 0, false, 0, -1},  {9, '1', 1, false, 0, 1},
    {9, '2', 2, false, 0, 2},   {9, 'R', 0, false, 0, -1},  {9, '3', 1, false, 0, 1},
    {9, '4', 2, false, 0, 2},   {9, '1', 3, false, 0, 3},   {9, '2', 0, true, 0, 4},
    {10, 'R', 0, false, 0, -1}, {10, '4', 1, false, 0, 1},  {10, '3', 2, false, 0, 2},
    {10, '2', 3, false, 0, 3},  {10, '1', 0, true, 0, 4},   {10, 'R', 0, false, 0, -1},
    {11, 'R', 0, false, 0, -1}, {11, '1', 1, false, 0, 1},  {11, '2', 2, false, 0, 2},
    {11, '3', 3, false, 0, 3},  {11, '4', 0, false, 1, 4},  {11, '1', 1, false, 1, 1},
    {11, '2', 2, false, 1, 2},  {11, '3', 3, false, 1, 3},  {11, '4', 0, false, 2, 4},
    {12, 'R', 0, false, 0, -1}, {12, '1', 1, false, 0, 1},  {12, 'B', 0, false, 0, 0},
    {12, '2', 1, false, 0, 1},  {12, 'B', 0, false, 0, 0},  {12, '3', 1, false, 0, 1},
    {12, 'B', 0, false, 0, 0},  {12, '4', 1, false, 0, 1},  {12, 'B', 0, false, 0, 0},
    {13, 'R', 0, false, 0, -1}, {13, '0', 1, false, 0, 1},  {13, '1', 2, false, 0, 2},
    {13, '2', 3, false, 0, 3},  {13, '3', 0, true, 0, 4},   {13, '4', 1, false, 0, 1},
    {13, '5', 2, false, 0, 2},  {13, '6', 3, false, 0, 3},  {13, '7', 0, true, 0, 4},
    {13, '8', 1, false, 0, 1},  {13, '9', 2, false, 0, 2},  {14, 'R', 0, false, 0, -1},
    {14, '2', 1, false, 0, 1},  {14, '3', 2, false, 0, 2},  {14, '4', 3, false, 0, 3},
    {14, '1', 0, true, 0, 4},   {14, 'R', 0, false, 0, -1}, {14, '1', 1, false, 0, 1},
    {14, '2', 2, false, 0, 2},  {14, '4', 3, false, 0, 3},  {14, '3', 0, true, 0, 4},
    {14, 'R', 0, false, 0, -1}, {14, '0', 1, false, 0, 1},  {14, '2', 2, false, 0, 2},
    {14, '3', 3, false, 0, 3},  {14, '4', 0, true, 0, 4},   {15, 'R', 0, false, 0, -1},
    {15, '1', 1, false, 0, 1},  {15, '2', 2, false, 0, 2},  {15, '3', 3, false, 0, 3},
    {15, '4', 0, false, 1, 4},  {15, '1', 1, false, 1, 1},  {15, '2', 2, false, 1, 2},
    {15, 'B', 1, false, 1, 1},  {15, '3', 2, false, 1, 2},  {15, '4', 3, false, 1, 3},
};

} // namespace models_test
