// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

// COMPONENT ExitBarPushLeft

lv_obj_t * ui_ExitBarPushLeft_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ExitBarPushLeft;
    cui_ExitBarPushLeft = lv_bar_create(comp_parent);
    lv_obj_set_width(cui_ExitBarPushLeft, 720);
    lv_obj_set_height(cui_ExitBarPushLeft, 70);
    lv_obj_set_x(cui_ExitBarPushLeft, 0);
    lv_obj_set_y(cui_ExitBarPushLeft, -10);
    lv_obj_set_align(cui_ExitBarPushLeft, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(cui_ExitBarPushLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_ExitBarPushLeft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ExitBarPushLeft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_set_style_radius(cui_ExitBarPushLeft, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_ExitBarPushLeft, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_ExitBarPushLeft, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_ExitBarPushLeft, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_ExitBarPushLeft,
                                                                                                       lv_obj_get_style_pad_right(cui_ExitBarPushLeft, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t * cui_ExitLabel2;
    cui_ExitLabel2 = lv_label_create(cui_ExitBarPushLeft);
    lv_obj_set_width(cui_ExitLabel2, 720);
    lv_obj_set_height(cui_ExitLabel2, 40);
    lv_obj_set_align(cui_ExitLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ExitLabel2, "Push left and hold joystick to exit");
    lv_obj_set_style_text_color(cui_ExitLabel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ExitLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(cui_ExitLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_ExitLabel2, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_EXITBARPUSHLEFT_NUM);
    children[UI_COMP_EXITBARPUSHLEFT_EXITBARPUSHLEFT] = cui_ExitBarPushLeft;
    children[UI_COMP_EXITBARPUSHLEFT_EXITLABEL2] = cui_ExitLabel2;
    lv_obj_add_event_cb(cui_ExitBarPushLeft, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ExitBarPushLeft, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ExitBarPushLeft_create_hook(cui_ExitBarPushLeft);
    return cui_ExitBarPushLeft;
}

