// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef _UI_COMP_EXITBARPRESS_H
#define _UI_COMP_EXITBARPRESS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ExitBarPress
#define UI_COMP_EXITBARPRESS_EXITBARPRESS 0
#define UI_COMP_EXITBARPRESS_EXITLABEL 1
#define _UI_COMP_EXITBARPRESS_NUM 2
lv_obj_t * ui_ExitBarPress_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
