// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

void ui_event_comp_TopBar_TopBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_TopBar = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCREEN_LOAD_ANIM_NONE, 0, 0, &ui_SettingsScreen_screen_init);
    }
}

// COMPONENT TopBar

lv_obj_t * ui_TopBar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_TopBar;
    cui_TopBar = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_TopBar, 720);
    lv_obj_set_height(cui_TopBar, 50);
    lv_obj_set_align(cui_TopBar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_TopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_TopBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_TopBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_TopBar, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Clock1;
    cui_Clock1 = lv_label_create(cui_TopBar);
    lv_obj_set_width(cui_Clock1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Clock1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Clock1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Clock1, "10:42");
    lv_obj_set_style_text_color(cui_Clock1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Clock1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Clock1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_GPS1;
    cui_GPS1 = lv_label_create(cui_TopBar);
    lv_obj_set_width(cui_GPS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_GPS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_GPS1, -120);
    lv_obj_set_y(cui_GPS1, 0);
    lv_obj_set_align(cui_GPS1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_GPS1, "BT   GPS");
    lv_obj_set_style_text_color(cui_GPS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_GPS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_GPS1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Battery1;
    cui_Battery1 = lv_bar_create(cui_TopBar);
    lv_bar_set_value(cui_Battery1, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_Battery1, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Battery1, 100);
    lv_obj_set_height(cui_Battery1, 20);
    lv_obj_set_align(cui_Battery1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(cui_Battery1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Battery1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_Battery1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Battery1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Battery1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_Battery1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_Battery1,
                                                                                                lv_obj_get_style_pad_right(cui_Battery1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(cui_Battery1);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label4, "30 km");
    lv_obj_set_style_text_color(cui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_TOPBAR_NUM);
    children[UI_COMP_TOPBAR_TOPBAR] = cui_TopBar;
    children[UI_COMP_TOPBAR_CLOCK1] = cui_Clock1;
    children[UI_COMP_TOPBAR_GPS1] = cui_GPS1;
    children[UI_COMP_TOPBAR_BATTERY1] = cui_Battery1;
    children[UI_COMP_TOPBAR_BATTERY1_LABEL4] = cui_Label4;
    lv_obj_add_event_cb(cui_TopBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_TopBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_TopBar, ui_event_comp_TopBar_TopBar, LV_EVENT_ALL, children);
    ui_comp_TopBar_create_hook(cui_TopBar);
    return cui_TopBar;
}

