// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

// COMPONENT GenericActionsComponent1

lv_obj_t * ui_GenericActionsComponent1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_GenericActionsComponent1;
    cui_GenericActionsComponent1 = lv_button_create(comp_parent);
    lv_obj_set_width(cui_GenericActionsComponent1, 320);
    lv_obj_set_height(cui_GenericActionsComponent1, 264);
    lv_obj_set_x(cui_GenericActionsComponent1, 0);
    lv_obj_set_y(cui_GenericActionsComponent1, -70);
    lv_obj_set_align(cui_GenericActionsComponent1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(cui_GenericActionsComponent1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_GenericActionsComponent1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_GenericActionsComponent1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_GenericActionsComponent1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_GenericActionsComponent1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_GenericActionsComponent1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_GenericActionsComponent1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_text);
    lv_obj_set_style_border_width(cui_GenericActionsComponent1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_GenericActionsElementContainer1;
    cui_GenericActionsElementContainer1 = lv_obj_create(cui_GenericActionsComponent1);
    lv_obj_remove_style_all(cui_GenericActionsElementContainer1);
    lv_obj_set_width(cui_GenericActionsElementContainer1, 320);
    lv_obj_set_height(cui_GenericActionsElementContainer1, 110);
    lv_obj_set_align(cui_GenericActionsElementContainer1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_GenericActionsElementContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_GenericActionsElementTitle1;
    cui_GenericActionsElementTitle1 = lv_label_create(cui_GenericActionsElementContainer1);
    lv_obj_set_height(cui_GenericActionsElementTitle1, 80);
    lv_obj_set_width(cui_GenericActionsElementTitle1, lv_pct(80));
    lv_obj_set_align(cui_GenericActionsElementTitle1, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(cui_GenericActionsElementTitle1, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(cui_GenericActionsElementTitle1, "Title 1");
    ui_object_set_themeable_style_property(cui_GenericActionsElementTitle1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_GenericActionsElementTitle1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_GenericActionsElementTitle1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_GenericActionsElementTitle1, &ui_font_IBMPlexSansMedium53,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_GenericActionsElementSubtitle1;
    cui_GenericActionsElementSubtitle1 = lv_label_create(cui_GenericActionsElementContainer1);
    lv_obj_set_height(cui_GenericActionsElementSubtitle1, 50);
    lv_obj_set_width(cui_GenericActionsElementSubtitle1, lv_pct(80));
    lv_obj_set_align(cui_GenericActionsElementSubtitle1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(cui_GenericActionsElementSubtitle1, "Subtitle 1");
    ui_object_set_themeable_style_property(cui_GenericActionsElementSubtitle1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_GenericActionsElementSubtitle1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_GenericActionsElementSubtitle1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_GenericActionsElementSubtitle1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_GENERICACTIONSCOMPONENT1_NUM);
    children[UI_COMP_GENERICACTIONSCOMPONENT1_GENERICACTIONSCOMPONENT1] = cui_GenericActionsComponent1;
    children[UI_COMP_GENERICACTIONSCOMPONENT1_GENERICACTIONSELEMENTCONTAINER1] = cui_GenericActionsElementContainer1;
    children[UI_COMP_GENERICACTIONSCOMPONENT1_GENERICACTIONSELEMENTCONTAINER1_GENERICACTIONSELEMENTTITLE1] =
        cui_GenericActionsElementTitle1;
    children[UI_COMP_GENERICACTIONSCOMPONENT1_GENERICACTIONSELEMENTCONTAINER1_GENERICACTIONSELEMENTSUBTITLE1] =
        cui_GenericActionsElementSubtitle1;
    lv_obj_add_event_cb(cui_GenericActionsComponent1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_GenericActionsComponent1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_GenericActionsComponent1_create_hook(cui_GenericActionsComponent1);
    return cui_GenericActionsComponent1;
}

