// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

lv_obj_t * ui_ActuatorsScreen = NULL;
lv_obj_t * ui_TopBar7 = NULL;
lv_obj_t * ui_RDScreenFlexPanel = NULL;
lv_obj_t * ui_RDScreenFlexPanelInner = NULL;
lv_obj_t * ui_ActuatorsLabel = NULL;
lv_obj_t * ui_ActuatorsFlexPanel = NULL;
lv_obj_t * ui_Actuator1 = NULL;
lv_obj_t * ui_TitleContainer1 = NULL;
lv_obj_t * ui_ActuatorLabels1 = NULL;
lv_obj_t * ui_Actuator1ShortLabel1 = NULL;
lv_obj_t * ui_Actuator1Label = NULL;
lv_obj_t * ui_ValueContainer1 = NULL;
lv_obj_t * ui_ActuatorShortLabel1 = NULL;
lv_obj_t * ui_MinusButton1 = NULL;
lv_obj_t * ui_MinusButtonContainer1 = NULL;
lv_obj_t * ui_MinusButtonLabel1 = NULL;
lv_obj_t * ui_PlusButton1 = NULL;
lv_obj_t * ui_MinusButtonContainer2 = NULL;
lv_obj_t * ui_MinusButtonLabel2 = NULL;
lv_obj_t * ui_Actuator2 = NULL;
lv_obj_t * ui_TitleContainer2 = NULL;
lv_obj_t * ui_ActuatorLabels2 = NULL;
lv_obj_t * ui_Actuator1ShortLabel2 = NULL;
lv_obj_t * ui_Actuator1Label1 = NULL;
lv_obj_t * ui_ValueContainer2 = NULL;
lv_obj_t * ui_ActuatorShortLabel2 = NULL;
lv_obj_t * ui_MinusButton2 = NULL;
lv_obj_t * ui_MinusButtonContainer3 = NULL;
lv_obj_t * ui_MinusButtonLabel3 = NULL;
lv_obj_t * ui_PlusButton2 = NULL;
lv_obj_t * ui_MinusButtonContainer4 = NULL;
lv_obj_t * ui_MinusButtonLabel4 = NULL;
lv_obj_t * ui_Actuator3 = NULL;
lv_obj_t * ui_TitleContainer3 = NULL;
lv_obj_t * ui_ActuatorLabels3 = NULL;
lv_obj_t * ui_Actuator1ShortLabel3 = NULL;
lv_obj_t * ui_Actuator1Label2 = NULL;
lv_obj_t * ui_ValueContainer3 = NULL;
lv_obj_t * ui_ActuatorShortLabel3 = NULL;
lv_obj_t * ui_MinusButton3 = NULL;
lv_obj_t * ui_MinusButtonContainer5 = NULL;
lv_obj_t * ui_MinusButtonLabel5 = NULL;
lv_obj_t * ui_PlusButton3 = NULL;
lv_obj_t * ui_MinusButtonContainer6 = NULL;
lv_obj_t * ui_MinusButtonLabel6 = NULL;
lv_obj_t * ui_ExitBarPull3 = NULL;
lv_obj_t * ui_ErrorWarningPanel3 = NULL;
lv_obj_t * ui_StatusPanel6 = NULL;
// event funtions

// build funtions

void ui_ActuatorsScreen_screen_init(void)
{
    ui_ActuatorsScreen = lv_obj_create(NULL);
    lv_obj_set_scroll_snap_x(ui_ActuatorsScreen, LV_SCROLL_SNAP_CENTER);
    ui_object_set_themeable_style_property(ui_ActuatorsScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_ActuatorsScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_TopBar7 = ui_TopBar_create(ui_ActuatorsScreen);
    lv_obj_set_x(ui_TopBar7, 0);
    lv_obj_set_y(ui_TopBar7, 0);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0

    ui_RDScreenFlexPanel = lv_obj_create(ui_ActuatorsScreen);
    lv_obj_set_width(ui_RDScreenFlexPanel, 760);
    lv_obj_set_height(ui_RDScreenFlexPanel, LV_SIZE_CONTENT);    /// 923
    lv_obj_set_x(ui_RDScreenFlexPanel, 0);
    lv_obj_set_y(ui_RDScreenFlexPanel, 195);
    lv_obj_set_align(ui_RDScreenFlexPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_RDScreenFlexPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RDScreenFlexPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_RDScreenFlexPanel, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_RDScreenFlexPanel,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RDScreenFlexPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_RDScreenFlexPanel, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_RDScreenFlexPanel, LV_SCROLL_SNAP_START);
    ui_object_set_themeable_style_property(ui_RDScreenFlexPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_RDScreenFlexPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_side(ui_RDScreenFlexPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RDScreenFlexPanelInner = lv_obj_create(ui_RDScreenFlexPanel);
    lv_obj_set_width(ui_RDScreenFlexPanelInner, 720);
    lv_obj_set_height(ui_RDScreenFlexPanelInner, 1050);
    lv_obj_set_align(ui_RDScreenFlexPanelInner, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_RDScreenFlexPanelInner, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_RDScreenFlexPanelInner, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_RDScreenFlexPanelInner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_RDScreenFlexPanelInner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_RDScreenFlexPanelInner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_RDScreenFlexPanelInner, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_RDScreenFlexPanelInner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_pad_row(ui_RDScreenFlexPanelInner, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RDScreenFlexPanelInner, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActuatorsLabel = lv_label_create(ui_RDScreenFlexPanelInner);
    lv_obj_set_width(ui_ActuatorsLabel, 660);
    lv_obj_set_height(ui_ActuatorsLabel, 50);
    lv_obj_set_align(ui_ActuatorsLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ActuatorsLabel, "Actuators\n");
    ui_object_set_themeable_style_property(ui_ActuatorsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_ActuatorsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_ActuatorsLabel, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ActuatorsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_ActuatorsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_ActuatorsFlexPanel = lv_obj_create(ui_RDScreenFlexPanelInner);
    lv_obj_set_width(ui_ActuatorsFlexPanel, 720);
    lv_obj_set_height(ui_ActuatorsFlexPanel, 850);
    lv_obj_set_x(ui_ActuatorsFlexPanel, 0);
    lv_obj_set_y(ui_ActuatorsFlexPanel, -37);
    lv_obj_set_align(ui_ActuatorsFlexPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ActuatorsFlexPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ActuatorsFlexPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ActuatorsFlexPanel, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ActuatorsFlexPanel, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_ActuatorsFlexPanel, LV_DIR_VER);
    ui_object_set_themeable_style_property(ui_ActuatorsFlexPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_ActuatorsFlexPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_side(ui_ActuatorsFlexPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ActuatorsFlexPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ActuatorsFlexPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ActuatorsFlexPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ActuatorsFlexPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ActuatorsFlexPanel, 42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ActuatorsFlexPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_ActuatorsFlexPanel, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_ActuatorsFlexPanel, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    ui_Actuator1 = lv_button_create(ui_ActuatorsFlexPanel);
    lv_obj_set_width(ui_Actuator1, 700);
    lv_obj_set_height(ui_Actuator1, 98);
    lv_obj_set_x(ui_Actuator1, 0);
    lv_obj_set_y(ui_Actuator1, 100);
    lv_obj_set_align(ui_Actuator1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Actuator1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Actuator1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_state(ui_Actuator1, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Actuator1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Actuator1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Actuator1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_Actuator1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_Actuator1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Actuator1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Actuator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Actuator1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Actuator1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Actuator1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Actuator1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Actuator1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Actuator1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Actuator1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_Actuator1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_focused);
    ui_object_set_themeable_style_property(ui_Actuator1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_focused);

    ui_TitleContainer1 = lv_obj_create(ui_Actuator1);
    lv_obj_remove_style_all(ui_TitleContainer1);
    lv_obj_set_width(ui_TitleContainer1, 136);
    lv_obj_set_height(ui_TitleContainer1, 98);
    lv_obj_set_align(ui_TitleContainer1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TitleContainer1, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_TitleContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActuatorLabels1 = lv_obj_create(ui_TitleContainer1);
    lv_obj_remove_style_all(ui_ActuatorLabels1);
    lv_obj_set_height(ui_ActuatorLabels1, 98);
    lv_obj_set_width(ui_ActuatorLabels1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_ActuatorLabels1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ActuatorLabels1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ActuatorLabels1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_state(ui_ActuatorLabels1, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_ActuatorLabels1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Actuator1ShortLabel1 = lv_label_create(ui_ActuatorLabels1);
    lv_obj_set_width(ui_Actuator1ShortLabel1, 130);
    lv_obj_set_height(ui_Actuator1ShortLabel1, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_x(ui_Actuator1ShortLabel1, 20);
    lv_obj_set_y(ui_Actuator1ShortLabel1, 0);
    lv_label_set_long_mode(ui_Actuator1ShortLabel1, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Actuator1ShortLabel1, "M1");
    lv_obj_add_state(ui_Actuator1ShortLabel1, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_Actuator1ShortLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Actuator1ShortLabel1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_Actuator1Label = lv_label_create(ui_ActuatorLabels1);
    lv_obj_set_width(ui_Actuator1Label, 130);
    lv_obj_set_height(ui_Actuator1Label, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_x(ui_Actuator1Label, 20);
    lv_obj_set_y(ui_Actuator1Label, 0);
    lv_obj_set_align(ui_Actuator1Label, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_Actuator1Label, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Actuator1Label, "Tilt Left Motor");
    lv_obj_add_state(ui_Actuator1Label, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_Actuator1Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Actuator1Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_Actuator1Label, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Actuator1Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator1Label, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator1Label, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_ValueContainer1 = lv_obj_create(ui_Actuator1);
    lv_obj_remove_style_all(ui_ValueContainer1);
    lv_obj_set_width(ui_ValueContainer1, 136);
    lv_obj_set_height(ui_ValueContainer1, 98);
    lv_obj_set_align(ui_ValueContainer1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ValueContainer1, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_ValueContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActuatorShortLabel1 = lv_label_create(ui_ValueContainer1);
    lv_obj_set_width(ui_ActuatorShortLabel1, 130);
    lv_obj_set_height(ui_ActuatorShortLabel1, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_align(ui_ActuatorShortLabel1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ActuatorShortLabel1, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ActuatorShortLabel1, "12.6");
    lv_obj_add_state(ui_ActuatorShortLabel1, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_ActuatorShortLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ActuatorShortLabel1, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_MinusButton1 = lv_button_create(ui_Actuator1);
    lv_obj_set_width(ui_MinusButton1, 132);
    lv_obj_set_height(ui_MinusButton1, 86);
    lv_obj_set_x(ui_MinusButton1, 0);
    lv_obj_set_y(ui_MinusButton1, -70);
    lv_obj_set_align(ui_MinusButton1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MinusButton1, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_MinusButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MinusButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MinusButton1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_MinusButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_MinusButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButton1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButton1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_MinusButton1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButton1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);

    ui_MinusButtonContainer1 = lv_obj_create(ui_MinusButton1);
    lv_obj_remove_style_all(ui_MinusButtonContainer1);
    lv_obj_set_width(ui_MinusButtonContainer1, 132);
    lv_obj_set_height(ui_MinusButtonContainer1, 86);
    lv_obj_set_align(ui_MinusButtonContainer1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MinusButtonContainer1, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_MinusButtonContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinusButtonLabel1 = lv_label_create(ui_MinusButtonContainer1);
    lv_obj_set_width(ui_MinusButtonLabel1, 132);
    lv_obj_set_height(ui_MinusButtonLabel1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_MinusButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinusButtonLabel1, "-");
    lv_obj_add_state(ui_MinusButtonLabel1, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_MinusButtonLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_MinusButtonLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinusButtonLabel1, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_PlusButton1 = lv_button_create(ui_Actuator1);
    lv_obj_set_width(ui_PlusButton1, 132);
    lv_obj_set_height(ui_PlusButton1, 86);
    lv_obj_set_x(ui_PlusButton1, 0);
    lv_obj_set_y(ui_PlusButton1, -70);
    lv_obj_set_align(ui_PlusButton1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PlusButton1, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_PlusButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PlusButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PlusButton1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PlusButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_PlusButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_PlusButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_PlusButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_PlusButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PlusButton1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_PlusButton1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_PlusButton1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_PlusButton1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);

    ui_MinusButtonContainer2 = lv_obj_create(ui_PlusButton1);
    lv_obj_remove_style_all(ui_MinusButtonContainer2);
    lv_obj_set_width(ui_MinusButtonContainer2, 132);
    lv_obj_set_height(ui_MinusButtonContainer2, 86);
    lv_obj_set_align(ui_MinusButtonContainer2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MinusButtonContainer2, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_MinusButtonContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinusButtonLabel2 = lv_label_create(ui_MinusButtonContainer2);
    lv_obj_set_width(ui_MinusButtonLabel2, 132);
    lv_obj_set_height(ui_MinusButtonLabel2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_MinusButtonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinusButtonLabel2, "+");
    lv_obj_add_state(ui_MinusButtonLabel2, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_MinusButtonLabel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_MinusButtonLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinusButtonLabel2, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_Actuator2 = lv_button_create(ui_ActuatorsFlexPanel);
    lv_obj_set_width(ui_Actuator2, 700);
    lv_obj_set_height(ui_Actuator2, 98);
    lv_obj_set_x(ui_Actuator2, 0);
    lv_obj_set_y(ui_Actuator2, 100);
    lv_obj_set_align(ui_Actuator2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Actuator2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Actuator2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_state(ui_Actuator2, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Actuator2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Actuator2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Actuator2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_Actuator2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_Actuator2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Actuator2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Actuator2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Actuator2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Actuator2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Actuator2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Actuator2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Actuator2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Actuator2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Actuator2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_Actuator2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_focused);
    ui_object_set_themeable_style_property(ui_Actuator2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_focused);

    ui_TitleContainer2 = lv_obj_create(ui_Actuator2);
    lv_obj_remove_style_all(ui_TitleContainer2);
    lv_obj_set_width(ui_TitleContainer2, 136);
    lv_obj_set_height(ui_TitleContainer2, 98);
    lv_obj_set_align(ui_TitleContainer2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TitleContainer2, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_TitleContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActuatorLabels2 = lv_obj_create(ui_TitleContainer2);
    lv_obj_remove_style_all(ui_ActuatorLabels2);
    lv_obj_set_height(ui_ActuatorLabels2, 98);
    lv_obj_set_width(ui_ActuatorLabels2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_ActuatorLabels2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ActuatorLabels2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ActuatorLabels2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_state(ui_ActuatorLabels2, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_ActuatorLabels2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Actuator1ShortLabel2 = lv_label_create(ui_ActuatorLabels2);
    lv_obj_set_width(ui_Actuator1ShortLabel2, 130);
    lv_obj_set_height(ui_Actuator1ShortLabel2, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_x(ui_Actuator1ShortLabel2, 20);
    lv_obj_set_y(ui_Actuator1ShortLabel2, 0);
    lv_label_set_long_mode(ui_Actuator1ShortLabel2, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Actuator1ShortLabel2, "M1");
    lv_obj_add_state(ui_Actuator1ShortLabel2, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_Actuator1ShortLabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Actuator1ShortLabel2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_Actuator1Label1 = lv_label_create(ui_ActuatorLabels2);
    lv_obj_set_width(ui_Actuator1Label1, 130);
    lv_obj_set_height(ui_Actuator1Label1, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_x(ui_Actuator1Label1, 20);
    lv_obj_set_y(ui_Actuator1Label1, 0);
    lv_obj_set_align(ui_Actuator1Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_Actuator1Label1, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Actuator1Label1, "Tilt Left Motor");
    lv_obj_add_state(ui_Actuator1Label1, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_Actuator1Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Actuator1Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_Actuator1Label1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Actuator1Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator1Label1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator1Label1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_ValueContainer2 = lv_obj_create(ui_Actuator2);
    lv_obj_remove_style_all(ui_ValueContainer2);
    lv_obj_set_width(ui_ValueContainer2, 136);
    lv_obj_set_height(ui_ValueContainer2, 98);
    lv_obj_set_align(ui_ValueContainer2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ValueContainer2, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_ValueContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActuatorShortLabel2 = lv_label_create(ui_ValueContainer2);
    lv_obj_set_width(ui_ActuatorShortLabel2, 130);
    lv_obj_set_height(ui_ActuatorShortLabel2, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_align(ui_ActuatorShortLabel2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ActuatorShortLabel2, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ActuatorShortLabel2, "12.6");
    lv_obj_add_state(ui_ActuatorShortLabel2, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_ActuatorShortLabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ActuatorShortLabel2, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_MinusButton2 = lv_button_create(ui_Actuator2);
    lv_obj_set_width(ui_MinusButton2, 132);
    lv_obj_set_height(ui_MinusButton2, 86);
    lv_obj_set_x(ui_MinusButton2, 0);
    lv_obj_set_y(ui_MinusButton2, -70);
    lv_obj_set_align(ui_MinusButton2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MinusButton2, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_MinusButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MinusButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MinusButton2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_MinusButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_MinusButton2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButton2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButton2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_MinusButton2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButton2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);

    ui_MinusButtonContainer3 = lv_obj_create(ui_MinusButton2);
    lv_obj_remove_style_all(ui_MinusButtonContainer3);
    lv_obj_set_width(ui_MinusButtonContainer3, 132);
    lv_obj_set_height(ui_MinusButtonContainer3, 86);
    lv_obj_set_align(ui_MinusButtonContainer3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MinusButtonContainer3, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_MinusButtonContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinusButtonLabel3 = lv_label_create(ui_MinusButtonContainer3);
    lv_obj_set_width(ui_MinusButtonLabel3, 132);
    lv_obj_set_height(ui_MinusButtonLabel3, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_MinusButtonLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinusButtonLabel3, "-");
    lv_obj_add_state(ui_MinusButtonLabel3, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_MinusButtonLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_MinusButtonLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinusButtonLabel3, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_PlusButton2 = lv_button_create(ui_Actuator2);
    lv_obj_set_width(ui_PlusButton2, 132);
    lv_obj_set_height(ui_PlusButton2, 86);
    lv_obj_set_x(ui_PlusButton2, 0);
    lv_obj_set_y(ui_PlusButton2, -70);
    lv_obj_set_align(ui_PlusButton2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PlusButton2, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_PlusButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PlusButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PlusButton2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PlusButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_PlusButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_PlusButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_PlusButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_PlusButton2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PlusButton2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_PlusButton2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_PlusButton2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_PlusButton2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);

    ui_MinusButtonContainer4 = lv_obj_create(ui_PlusButton2);
    lv_obj_remove_style_all(ui_MinusButtonContainer4);
    lv_obj_set_width(ui_MinusButtonContainer4, 132);
    lv_obj_set_height(ui_MinusButtonContainer4, 86);
    lv_obj_set_align(ui_MinusButtonContainer4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MinusButtonContainer4, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_MinusButtonContainer4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinusButtonLabel4 = lv_label_create(ui_MinusButtonContainer4);
    lv_obj_set_width(ui_MinusButtonLabel4, 132);
    lv_obj_set_height(ui_MinusButtonLabel4, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_MinusButtonLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinusButtonLabel4, "+");
    lv_obj_add_state(ui_MinusButtonLabel4, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_MinusButtonLabel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_MinusButtonLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinusButtonLabel4, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel4, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel4, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_Actuator3 = lv_button_create(ui_ActuatorsFlexPanel);
    lv_obj_set_width(ui_Actuator3, 700);
    lv_obj_set_height(ui_Actuator3, 98);
    lv_obj_set_x(ui_Actuator3, 0);
    lv_obj_set_y(ui_Actuator3, 100);
    lv_obj_set_align(ui_Actuator3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Actuator3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Actuator3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_state(ui_Actuator3, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Actuator3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Actuator3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Actuator3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_Actuator3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_Actuator3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Actuator3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Actuator3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Actuator3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Actuator3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Actuator3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Actuator3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Actuator3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Actuator3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Actuator3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_Actuator3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_focused);
    ui_object_set_themeable_style_property(ui_Actuator3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_focused);

    ui_TitleContainer3 = lv_obj_create(ui_Actuator3);
    lv_obj_remove_style_all(ui_TitleContainer3);
    lv_obj_set_width(ui_TitleContainer3, 136);
    lv_obj_set_height(ui_TitleContainer3, 98);
    lv_obj_set_align(ui_TitleContainer3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TitleContainer3, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_TitleContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActuatorLabels3 = lv_obj_create(ui_TitleContainer3);
    lv_obj_remove_style_all(ui_ActuatorLabels3);
    lv_obj_set_height(ui_ActuatorLabels3, 98);
    lv_obj_set_width(ui_ActuatorLabels3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_ActuatorLabels3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ActuatorLabels3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ActuatorLabels3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_state(ui_ActuatorLabels3, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_ActuatorLabels3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Actuator1ShortLabel3 = lv_label_create(ui_ActuatorLabels3);
    lv_obj_set_width(ui_Actuator1ShortLabel3, 130);
    lv_obj_set_height(ui_Actuator1ShortLabel3, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_x(ui_Actuator1ShortLabel3, 20);
    lv_obj_set_y(ui_Actuator1ShortLabel3, 0);
    lv_label_set_long_mode(ui_Actuator1ShortLabel3, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Actuator1ShortLabel3, "M1");
    lv_obj_add_state(ui_Actuator1ShortLabel3, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_Actuator1ShortLabel3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Actuator1ShortLabel3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator1ShortLabel3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_Actuator1Label2 = lv_label_create(ui_ActuatorLabels3);
    lv_obj_set_width(ui_Actuator1Label2, 130);
    lv_obj_set_height(ui_Actuator1Label2, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_x(ui_Actuator1Label2, 20);
    lv_obj_set_y(ui_Actuator1Label2, 0);
    lv_obj_set_align(ui_Actuator1Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_Actuator1Label2, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Actuator1Label2, "Tilt Left Motor");
    lv_obj_add_state(ui_Actuator1Label2, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_Actuator1Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_Actuator1Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_Actuator1Label2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Actuator1Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Actuator1Label2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Actuator1Label2, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_ValueContainer3 = lv_obj_create(ui_Actuator3);
    lv_obj_remove_style_all(ui_ValueContainer3);
    lv_obj_set_width(ui_ValueContainer3, 136);
    lv_obj_set_height(ui_ValueContainer3, 98);
    lv_obj_set_align(ui_ValueContainer3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ValueContainer3, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_ValueContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActuatorShortLabel3 = lv_label_create(ui_ValueContainer3);
    lv_obj_set_width(ui_ActuatorShortLabel3, 130);
    lv_obj_set_height(ui_ActuatorShortLabel3, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_align(ui_ActuatorShortLabel3, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ActuatorShortLabel3, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ActuatorShortLabel3, "12.6");
    lv_obj_add_state(ui_ActuatorShortLabel3, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_ActuatorShortLabel3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ActuatorShortLabel3, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_ActuatorShortLabel3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_MinusButton3 = lv_button_create(ui_Actuator3);
    lv_obj_set_width(ui_MinusButton3, 132);
    lv_obj_set_height(ui_MinusButton3, 86);
    lv_obj_set_x(ui_MinusButton3, 0);
    lv_obj_set_y(ui_MinusButton3, -70);
    lv_obj_set_align(ui_MinusButton3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MinusButton3, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_MinusButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MinusButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MinusButton3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_MinusButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_MinusButton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButton3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButton3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_MinusButton3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButton3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);

    ui_MinusButtonContainer5 = lv_obj_create(ui_MinusButton3);
    lv_obj_remove_style_all(ui_MinusButtonContainer5);
    lv_obj_set_width(ui_MinusButtonContainer5, 132);
    lv_obj_set_height(ui_MinusButtonContainer5, 86);
    lv_obj_set_align(ui_MinusButtonContainer5, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MinusButtonContainer5, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_MinusButtonContainer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinusButtonLabel5 = lv_label_create(ui_MinusButtonContainer5);
    lv_obj_set_width(ui_MinusButtonLabel5, 132);
    lv_obj_set_height(ui_MinusButtonLabel5, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_MinusButtonLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinusButtonLabel5, "-");
    lv_obj_add_state(ui_MinusButtonLabel5, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_MinusButtonLabel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_MinusButtonLabel5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinusButtonLabel5, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel5, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel5, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_PlusButton3 = lv_button_create(ui_Actuator3);
    lv_obj_set_width(ui_PlusButton3, 132);
    lv_obj_set_height(ui_PlusButton3, 86);
    lv_obj_set_x(ui_PlusButton3, 0);
    lv_obj_set_y(ui_PlusButton3, -70);
    lv_obj_set_align(ui_PlusButton3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PlusButton3, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_PlusButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PlusButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PlusButton3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PlusButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_PlusButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_PlusButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_PlusButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_PlusButton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PlusButton3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_PlusButton3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_PlusButton3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_PlusButton3, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);

    ui_MinusButtonContainer6 = lv_obj_create(ui_PlusButton3);
    lv_obj_remove_style_all(ui_MinusButtonContainer6);
    lv_obj_set_width(ui_MinusButtonContainer6, 132);
    lv_obj_set_height(ui_MinusButtonContainer6, 86);
    lv_obj_set_align(ui_MinusButtonContainer6, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MinusButtonContainer6, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(ui_MinusButtonContainer6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinusButtonLabel6 = lv_label_create(ui_MinusButtonContainer6);
    lv_obj_set_width(ui_MinusButtonLabel6, 132);
    lv_obj_set_height(ui_MinusButtonLabel6, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_MinusButtonLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinusButtonLabel6, "+");
    lv_obj_add_state(ui_MinusButtonLabel6, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(ui_MinusButtonLabel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_MinusButtonLabel6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinusButtonLabel6, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel6, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MinusButtonLabel6, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_ExitBarPull3 = ui_ExitBarPull_create(ui_ActuatorsScreen);
    lv_obj_set_x(ui_ExitBarPull3, 0);
    lv_obj_set_y(ui_ExitBarPull3, -10);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0

    ui_ErrorWarningPanel3 = ui_ErrorWarningPanel_create(ui_ActuatorsScreen);
    lv_obj_set_x(ui_ErrorWarningPanel3, 0);
    lv_obj_set_y(ui_ErrorWarningPanel3, 180);

    ui_StatusPanel6 = ui_StatusPanel_create(ui_ActuatorsScreen);
    lv_obj_set_x(ui_StatusPanel6, 0);
    lv_obj_set_y(ui_StatusPanel6, 50);

}

void ui_ActuatorsScreen_screen_destroy(void)
{
    if(ui_ActuatorsScreen) lv_obj_del(ui_ActuatorsScreen);

    // NULL screen variables
    ui_ActuatorsScreen = NULL;
    ui_TopBar7 = NULL;
    ui_RDScreenFlexPanel = NULL;
    ui_RDScreenFlexPanelInner = NULL;
    ui_ActuatorsLabel = NULL;
    ui_ActuatorsFlexPanel = NULL;
    ui_Actuator1 = NULL;
    ui_TitleContainer1 = NULL;
    ui_ActuatorLabels1 = NULL;
    ui_Actuator1ShortLabel1 = NULL;
    ui_Actuator1Label = NULL;
    ui_ValueContainer1 = NULL;
    ui_ActuatorShortLabel1 = NULL;
    ui_MinusButton1 = NULL;
    ui_MinusButtonContainer1 = NULL;
    ui_MinusButtonLabel1 = NULL;
    ui_PlusButton1 = NULL;
    ui_MinusButtonContainer2 = NULL;
    ui_MinusButtonLabel2 = NULL;
    ui_Actuator2 = NULL;
    ui_TitleContainer2 = NULL;
    ui_ActuatorLabels2 = NULL;
    ui_Actuator1ShortLabel2 = NULL;
    ui_Actuator1Label1 = NULL;
    ui_ValueContainer2 = NULL;
    ui_ActuatorShortLabel2 = NULL;
    ui_MinusButton2 = NULL;
    ui_MinusButtonContainer3 = NULL;
    ui_MinusButtonLabel3 = NULL;
    ui_PlusButton2 = NULL;
    ui_MinusButtonContainer4 = NULL;
    ui_MinusButtonLabel4 = NULL;
    ui_Actuator3 = NULL;
    ui_TitleContainer3 = NULL;
    ui_ActuatorLabels3 = NULL;
    ui_Actuator1ShortLabel3 = NULL;
    ui_Actuator1Label2 = NULL;
    ui_ValueContainer3 = NULL;
    ui_ActuatorShortLabel3 = NULL;
    ui_MinusButton3 = NULL;
    ui_MinusButtonContainer5 = NULL;
    ui_MinusButtonLabel5 = NULL;
    ui_PlusButton3 = NULL;
    ui_MinusButtonContainer6 = NULL;
    ui_MinusButtonLabel6 = NULL;
    ui_ExitBarPull3 = NULL;
    ui_ErrorWarningPanel3 = NULL;
    ui_StatusPanel6 = NULL;

}
