// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef UI_ACTUATORSSCREEN_H
#define UI_ACTUATORSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ActuatorsScreen
extern void ui_ActuatorsScreen_screen_init(void);
extern void ui_ActuatorsScreen_screen_destroy(void);
extern lv_obj_t * ui_ActuatorsScreen;
extern lv_obj_t * ui_TopBar7;
extern lv_obj_t * ui_RDScreenFlexPanel;
extern lv_obj_t * ui_RDScreenFlexPanelInner;
extern lv_obj_t * ui_ActuatorsLabel;
extern lv_obj_t * ui_ActuatorsFlexPanel;
extern lv_obj_t * ui_ActuatorComponent;
extern lv_obj_t * ui_ExitBarPull3;
extern lv_obj_t * ui_ErrorWarningPanel3;
extern lv_obj_t * ui_StatusPanel6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

