// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef UI_DIAGNOSTICSSCREEN_H
#define UI_DIAGNOSTICSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DiagnosticsScreen
extern void ui_DiagnosticsScreen_screen_init(void);
extern void ui_DiagnosticsScreen_screen_destroy(void);
extern lv_obj_t * ui_DiagnosticsScreen;
extern lv_obj_t * ui_TopBar10;
extern lv_obj_t * ui_SpecificSettingsFlexPanel1;
extern lv_obj_t * ui_SpecificSettingsInnerPanel1;
extern lv_obj_t * ui_DiagnosticsTitleContainer;
extern lv_obj_t * ui_DianosticsTitleLabel;
extern lv_obj_t * ui_DiagnosticsFreqLabel;
extern lv_obj_t * ui_DiagnosticsFlexRows;
extern lv_obj_t * ui_DiagnosticComponent;
extern lv_obj_t * ui_ExitBarPull6;
extern lv_obj_t * ui_ErrorWarningPanel8;
extern lv_obj_t * ui_StatusPanel9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

