// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_TopBar2;
extern lv_obj_t * ui_SettingsPanel;
extern lv_obj_t * ui_Button;
extern lv_obj_t * ui_ButtonLabel;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_ButtonLabel1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_ButtonLabel2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_ButtonLabel3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_ButtonLabel4;
extern lv_obj_t * ui_BottomMenu2;
extern lv_obj_t * ui_Mode7;
extern lv_obj_t * ui_LeftButtonLabel9;
extern void ui_event_Mode4(lv_event_t * e);
extern lv_obj_t * ui_Mode4;
extern lv_obj_t * ui_LeftButtonLabel6;
extern void ui_event_Mode5(lv_event_t * e);
extern lv_obj_t * ui_Mode5;
extern lv_obj_t * ui_LeftButtonLabel7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

