// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

lv_obj_t * ui_SeatAdjustmentFlexScreen = NULL;
lv_obj_t * ui_TopBar4 = NULL;
lv_obj_t * ui_SeatAdjustmentScreenFlexPanel = NULL;
lv_obj_t * ui_SeatFunctionsButtonsPanel = NULL;
lv_obj_t * ui_SeatFunctionsLabel = NULL;
lv_obj_t * ui_SeatButton1 = NULL;
lv_obj_t * ui_SeatButtonContainer1 = NULL;
lv_obj_t * ui_SeatButtonLabel1 = NULL;
lv_obj_t * ui_SeatButtonValue1 = NULL;
lv_obj_t * ui_SeatButton2 = NULL;
lv_obj_t * ui_SeatButtonContainer2 = NULL;
lv_obj_t * ui_SeatButtonLabel2 = NULL;
lv_obj_t * ui_SeatButtonValue2 = NULL;
lv_obj_t * ui_SeatButton3 = NULL;
lv_obj_t * ui_SeatButtonContainer3 = NULL;
lv_obj_t * ui_SeatButtonLabel3 = NULL;
lv_obj_t * ui_SeatButtonValue3 = NULL;
lv_obj_t * ui_SeatButton4 = NULL;
lv_obj_t * ui_SeatButtonContainer4 = NULL;
lv_obj_t * ui_SeatButtonLabel4 = NULL;
lv_obj_t * ui_SeatButtonValue4 = NULL;
lv_obj_t * ui_SeatButton5 = NULL;
lv_obj_t * ui_SeatButtonContainer5 = NULL;
lv_obj_t * ui_SeatButtonLabel5 = NULL;
lv_obj_t * ui_SeatButton6 = NULL;
lv_obj_t * ui_SeatButtonContainer6 = NULL;
lv_obj_t * ui_SeatButtonLabel6 = NULL;
lv_obj_t * ui_ExitBarPull1 = NULL;
lv_obj_t * ui_SeatAdjustmentPanel = NULL;
lv_obj_t * ui_AngleSettingLabel = NULL;
lv_obj_t * ui_AngleIndicator = NULL;
lv_obj_t * ui_AngleLabel = NULL;
lv_obj_t * ui_MaxAngleLabel = NULL;
lv_obj_t * ui_SeatAdjustmentButton1 = NULL;
lv_obj_t * ui_SeatAdjustmentButtonContainer1 = NULL;
lv_obj_t * ui_SeatAdjustmentButtonLabel1 = NULL;
lv_obj_t * ui_SeatAdjustmentButton2 = NULL;
lv_obj_t * ui_SeatAdjustmentButtonContainer2 = NULL;
lv_obj_t * ui_SeatAdjustmentButtonLabel2 = NULL;
lv_obj_t * ui_SeatAdjustmentButton3 = NULL;
lv_obj_t * ui_SeatAdjustmentButtonContainer3 = NULL;
lv_obj_t * ui_SeatAdjustmentButtonLabel3 = NULL;
lv_obj_t * ui_SeatAdjustmentButton4 = NULL;
lv_obj_t * ui_SeatAdjustmentButtonContainer4 = NULL;
lv_obj_t * ui_SeatAdjustmentButtonLabel4 = NULL;
lv_obj_t * ui_SeatAdjustmentButton5 = NULL;
lv_obj_t * ui_SeatAdjustmentButtonContainer5 = NULL;
lv_obj_t * ui_SeatAdjustmentButtonLabel5 = NULL;
lv_obj_t * ui_ExitBarPushLeft = NULL;
lv_obj_t * ui_ErrorWarningPanel1 = NULL;
lv_obj_t * ui_StatusPanel3 = NULL;
// event funtions

// build funtions

void ui_SeatAdjustmentFlexScreen_screen_init(void)
{
    ui_SeatAdjustmentFlexScreen = lv_obj_create(NULL);
    lv_obj_set_scroll_snap_x(ui_SeatAdjustmentFlexScreen, LV_SCROLL_SNAP_CENTER);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentFlexScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentFlexScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_TopBar4 = ui_TopBar_create(ui_SeatAdjustmentFlexScreen);
    lv_obj_set_x(ui_TopBar4, 0);
    lv_obj_set_y(ui_TopBar4, 0);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0

    ui_SeatAdjustmentScreenFlexPanel = lv_obj_create(ui_SeatAdjustmentFlexScreen);
    lv_obj_set_width(ui_SeatAdjustmentScreenFlexPanel, 760);
    lv_obj_set_height(ui_SeatAdjustmentScreenFlexPanel, LV_SIZE_CONTENT);    /// 923
    lv_obj_set_x(ui_SeatAdjustmentScreenFlexPanel, 0);
    lv_obj_set_y(ui_SeatAdjustmentScreenFlexPanel, 195);
    lv_obj_set_align(ui_SeatAdjustmentScreenFlexPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_SeatAdjustmentScreenFlexPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SeatAdjustmentScreenFlexPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_SeatAdjustmentScreenFlexPanel, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_SeatAdjustmentScreenFlexPanel,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_SeatAdjustmentScreenFlexPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_SeatAdjustmentScreenFlexPanel, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_SeatAdjustmentScreenFlexPanel, LV_SCROLL_SNAP_START);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentScreenFlexPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentScreenFlexPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_background);
    lv_obj_set_style_border_side(ui_SeatAdjustmentScreenFlexPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatFunctionsButtonsPanel = lv_obj_create(ui_SeatAdjustmentScreenFlexPanel);
    lv_obj_set_width(ui_SeatFunctionsButtonsPanel, 720);
    lv_obj_set_height(ui_SeatFunctionsButtonsPanel, 1050);
    lv_obj_set_align(ui_SeatFunctionsButtonsPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_SeatFunctionsButtonsPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SeatFunctionsButtonsPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_SeatFunctionsButtonsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SeatFunctionsButtonsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatFunctionsButtonsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatFunctionsButtonsPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatFunctionsButtonsPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_background);
    lv_obj_set_style_pad_row(ui_SeatFunctionsButtonsPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SeatFunctionsButtonsPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatFunctionsLabel = lv_label_create(ui_SeatFunctionsButtonsPanel);
    lv_obj_set_width(ui_SeatFunctionsLabel, 660);
    lv_obj_set_height(ui_SeatFunctionsLabel, 50);
    lv_obj_set_align(ui_SeatFunctionsLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SeatFunctionsLabel, "Seat Functions");
    ui_object_set_themeable_style_property(ui_SeatFunctionsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatFunctionsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_SeatFunctionsLabel, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatFunctionsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatFunctionsLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_SeatButton1 = lv_button_create(ui_SeatFunctionsButtonsPanel);
    lv_obj_set_width(ui_SeatButton1, 320);
    lv_obj_set_height(ui_SeatButton1, 264);
    lv_obj_set_x(ui_SeatButton1, 0);
    lv_obj_set_y(ui_SeatButton1, -70);
    lv_obj_set_align(ui_SeatButton1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatButton1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButtonContainer1 = lv_obj_create(ui_SeatButton1);
    lv_obj_remove_style_all(ui_SeatButtonContainer1);
    lv_obj_set_width(ui_SeatButtonContainer1, 320);
    lv_obj_set_height(ui_SeatButtonContainer1, 110);
    lv_obj_set_align(ui_SeatButtonContainer1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatButtonContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatButtonLabel1 = lv_label_create(ui_SeatButtonContainer1);
    lv_obj_set_width(ui_SeatButtonLabel1, 240);
    lv_obj_set_height(ui_SeatButtonLabel1, 50);
    lv_obj_set_align(ui_SeatButtonLabel1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SeatButtonLabel1, "Elevation");
    ui_object_set_themeable_style_property(ui_SeatButtonLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButtonLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatButtonLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatButtonLabel1, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButtonValue1 = lv_label_create(ui_SeatButtonContainer1);
    lv_obj_set_width(ui_SeatButtonValue1, 240);
    lv_obj_set_height(ui_SeatButtonValue1, 50);
    lv_obj_set_align(ui_SeatButtonValue1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SeatButtonValue1, "4.0 in");
    ui_object_set_themeable_style_property(ui_SeatButtonValue1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButtonValue1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatButtonValue1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatButtonValue1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButton2 = lv_button_create(ui_SeatFunctionsButtonsPanel);
    lv_obj_set_width(ui_SeatButton2, 320);
    lv_obj_set_height(ui_SeatButton2, 264);
    lv_obj_set_x(ui_SeatButton2, 0);
    lv_obj_set_y(ui_SeatButton2, -70);
    lv_obj_set_align(ui_SeatButton2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatButton2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatButton2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButtonContainer2 = lv_obj_create(ui_SeatButton2);
    lv_obj_remove_style_all(ui_SeatButtonContainer2);
    lv_obj_set_width(ui_SeatButtonContainer2, 320);
    lv_obj_set_height(ui_SeatButtonContainer2, 110);
    lv_obj_set_align(ui_SeatButtonContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatButtonContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatButtonLabel2 = lv_label_create(ui_SeatButtonContainer2);
    lv_obj_set_width(ui_SeatButtonLabel2, 240);
    lv_obj_set_height(ui_SeatButtonLabel2, 50);
    lv_obj_set_align(ui_SeatButtonLabel2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SeatButtonLabel2, "Real Tilt");
    ui_object_set_themeable_style_property(ui_SeatButtonLabel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButtonLabel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatButtonLabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatButtonLabel2, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButtonValue2 = lv_label_create(ui_SeatButtonContainer2);
    lv_obj_set_width(ui_SeatButtonValue2, 240);
    lv_obj_set_height(ui_SeatButtonValue2, 50);
    lv_obj_set_align(ui_SeatButtonValue2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SeatButtonValue2, "12°");
    ui_object_set_themeable_style_property(ui_SeatButtonValue2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButtonValue2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatButtonValue2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatButtonValue2, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButton3 = lv_button_create(ui_SeatFunctionsButtonsPanel);
    lv_obj_set_width(ui_SeatButton3, 320);
    lv_obj_set_height(ui_SeatButton3, 264);
    lv_obj_set_x(ui_SeatButton3, 0);
    lv_obj_set_y(ui_SeatButton3, -70);
    lv_obj_set_align(ui_SeatButton3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatButton3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatButton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButtonContainer3 = lv_obj_create(ui_SeatButton3);
    lv_obj_remove_style_all(ui_SeatButtonContainer3);
    lv_obj_set_width(ui_SeatButtonContainer3, 320);
    lv_obj_set_height(ui_SeatButtonContainer3, 110);
    lv_obj_set_align(ui_SeatButtonContainer3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatButtonContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatButtonLabel3 = lv_label_create(ui_SeatButtonContainer3);
    lv_obj_set_width(ui_SeatButtonLabel3, 240);
    lv_obj_set_height(ui_SeatButtonLabel3, 50);
    lv_obj_set_align(ui_SeatButtonLabel3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SeatButtonLabel3, "FW Tilt");
    ui_object_set_themeable_style_property(ui_SeatButtonLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButtonLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatButtonLabel3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatButtonLabel3, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButtonValue3 = lv_label_create(ui_SeatButtonContainer3);
    lv_obj_set_width(ui_SeatButtonValue3, 240);
    lv_obj_set_height(ui_SeatButtonValue3, 50);
    lv_obj_set_align(ui_SeatButtonValue3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SeatButtonValue3, "0°");
    ui_object_set_themeable_style_property(ui_SeatButtonValue3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButtonValue3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatButtonValue3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatButtonValue3, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButton4 = lv_button_create(ui_SeatFunctionsButtonsPanel);
    lv_obj_set_width(ui_SeatButton4, 320);
    lv_obj_set_height(ui_SeatButton4, 264);
    lv_obj_set_x(ui_SeatButton4, 0);
    lv_obj_set_y(ui_SeatButton4, -70);
    lv_obj_set_align(ui_SeatButton4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatButton4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatButton4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatButton4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatButton4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButton4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatButton4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButtonContainer4 = lv_obj_create(ui_SeatButton4);
    lv_obj_remove_style_all(ui_SeatButtonContainer4);
    lv_obj_set_width(ui_SeatButtonContainer4, 320);
    lv_obj_set_height(ui_SeatButtonContainer4, 110);
    lv_obj_set_align(ui_SeatButtonContainer4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatButtonContainer4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatButtonLabel4 = lv_label_create(ui_SeatButtonContainer4);
    lv_obj_set_width(ui_SeatButtonLabel4, 240);
    lv_obj_set_height(ui_SeatButtonLabel4, 50);
    lv_obj_set_align(ui_SeatButtonLabel4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SeatButtonLabel4, "Side Tilt");
    ui_object_set_themeable_style_property(ui_SeatButtonLabel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButtonLabel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatButtonLabel4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatButtonLabel4, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButtonValue4 = lv_label_create(ui_SeatButtonContainer4);
    lv_obj_set_width(ui_SeatButtonValue4, 240);
    lv_obj_set_height(ui_SeatButtonValue4, 50);
    lv_obj_set_align(ui_SeatButtonValue4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SeatButtonValue4, "0°");
    ui_object_set_themeable_style_property(ui_SeatButtonValue4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButtonValue4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatButtonValue4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatButtonValue4, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButton5 = lv_button_create(ui_SeatFunctionsButtonsPanel);
    lv_obj_set_width(ui_SeatButton5, 320);
    lv_obj_set_height(ui_SeatButton5, 162);
    lv_obj_set_x(ui_SeatButton5, 0);
    lv_obj_set_y(ui_SeatButton5, -70);
    lv_obj_set_align(ui_SeatButton5, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatButton5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatButton5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButtonContainer5 = lv_obj_create(ui_SeatButton5);
    lv_obj_remove_style_all(ui_SeatButtonContainer5);
    lv_obj_set_width(ui_SeatButtonContainer5, 320);
    lv_obj_set_height(ui_SeatButtonContainer5, 110);
    lv_obj_set_align(ui_SeatButtonContainer5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatButtonContainer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatButtonLabel5 = lv_label_create(ui_SeatButtonContainer5);
    lv_obj_set_width(ui_SeatButtonLabel5, 240);
    lv_obj_set_height(ui_SeatButtonLabel5, 50);
    lv_obj_set_align(ui_SeatButtonLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SeatButtonLabel5, "Static");
    ui_object_set_themeable_style_property(ui_SeatButtonLabel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButtonLabel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatButtonLabel5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatButtonLabel5, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButton6 = lv_button_create(ui_SeatFunctionsButtonsPanel);
    lv_obj_set_width(ui_SeatButton6, 320);
    lv_obj_set_height(ui_SeatButton6, 162);
    lv_obj_set_x(ui_SeatButton6, 0);
    lv_obj_set_y(ui_SeatButton6, -70);
    lv_obj_set_align(ui_SeatButton6, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatButton6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatButton6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatButton6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatButton6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButton6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatButton6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatButtonContainer6 = lv_obj_create(ui_SeatButton6);
    lv_obj_remove_style_all(ui_SeatButtonContainer6);
    lv_obj_set_width(ui_SeatButtonContainer6, 320);
    lv_obj_set_height(ui_SeatButtonContainer6, 110);
    lv_obj_set_align(ui_SeatButtonContainer6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatButtonContainer6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatButtonLabel6 = lv_label_create(ui_SeatButtonContainer6);
    lv_obj_set_width(ui_SeatButtonLabel6, 240);
    lv_obj_set_height(ui_SeatButtonLabel6, 50);
    lv_obj_set_align(ui_SeatButtonLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SeatButtonLabel6, "Dynamic");
    ui_object_set_themeable_style_property(ui_SeatButtonLabel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatButtonLabel6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatButtonLabel6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatButtonLabel6, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExitBarPull1 = ui_ExitBarPull_create(ui_SeatFunctionsButtonsPanel);
    lv_obj_set_x(ui_ExitBarPull1, 0);
    lv_obj_set_y(ui_ExitBarPull1, -10);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0

    ui_SeatAdjustmentPanel = lv_obj_create(ui_SeatAdjustmentScreenFlexPanel);
    lv_obj_set_width(ui_SeatAdjustmentPanel, 720);
    lv_obj_set_height(ui_SeatAdjustmentPanel, 900);
    lv_obj_set_align(ui_SeatAdjustmentPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_SeatAdjustmentPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SeatAdjustmentPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_SeatAdjustmentPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SeatAdjustmentPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_pad_row(ui_SeatAdjustmentPanel, 21, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SeatAdjustmentPanel, 21, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AngleSettingLabel = lv_label_create(ui_SeatAdjustmentPanel);
    lv_obj_set_width(ui_AngleSettingLabel, 660);
    lv_obj_set_height(ui_AngleSettingLabel, 50);
    lv_obj_set_align(ui_AngleSettingLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AngleSettingLabel, "Real Tilt");
    ui_object_set_themeable_style_property(ui_AngleSettingLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_AngleSettingLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_AngleSettingLabel, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_AngleSettingLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_AngleSettingLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_AngleIndicator = lv_obj_create(ui_SeatAdjustmentPanel);
    lv_obj_remove_style_all(ui_AngleIndicator);
    lv_obj_set_width(ui_AngleIndicator, 600);
    lv_obj_set_height(ui_AngleIndicator, LV_SIZE_CONTENT);    /// 250
    lv_obj_set_align(ui_AngleIndicator, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AngleIndicator, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AngleIndicator, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AngleIndicator,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_AngleLabel = lv_label_create(ui_AngleIndicator);
    lv_obj_set_height(ui_AngleLabel, 220);
    lv_obj_set_width(ui_AngleLabel, LV_SIZE_CONTENT);   /// 700
    lv_obj_set_align(ui_AngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AngleLabel, "12°");
    ui_object_set_themeable_style_property(ui_AngleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_AngleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_AngleLabel, &ui_font_IBMPlexSansMedium264, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_AngleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_AngleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_MaxAngleLabel = lv_label_create(ui_AngleIndicator);
    lv_obj_set_width(ui_MaxAngleLabel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_MaxAngleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxAngleLabel, 30);
    lv_obj_set_y(ui_MaxAngleLabel, 0);
    lv_obj_set_align(ui_MaxAngleLabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_MaxAngleLabel, "of 25°");
    ui_object_set_themeable_style_property(ui_MaxAngleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_MaxAngleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_MaxAngleLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MaxAngleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_MaxAngleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_SeatAdjustmentButton1 = lv_button_create(ui_SeatAdjustmentPanel);
    lv_obj_set_width(ui_SeatAdjustmentButton1, 320);
    lv_obj_set_height(ui_SeatAdjustmentButton1, 162);
    lv_obj_set_x(ui_SeatAdjustmentButton1, 0);
    lv_obj_set_y(ui_SeatAdjustmentButton1, -70);
    lv_obj_set_align(ui_SeatAdjustmentButton1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatAdjustmentButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatAdjustmentButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatAdjustmentButton1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatAdjustmentButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatAdjustmentButtonContainer1 = lv_obj_create(ui_SeatAdjustmentButton1);
    lv_obj_remove_style_all(ui_SeatAdjustmentButtonContainer1);
    lv_obj_set_width(ui_SeatAdjustmentButtonContainer1, 320);
    lv_obj_set_height(ui_SeatAdjustmentButtonContainer1, 110);
    lv_obj_set_align(ui_SeatAdjustmentButtonContainer1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatAdjustmentButtonContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatAdjustmentButtonLabel1 = lv_label_create(ui_SeatAdjustmentButtonContainer1);
    lv_obj_set_width(ui_SeatAdjustmentButtonLabel1, 240);
    lv_obj_set_height(ui_SeatAdjustmentButtonLabel1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SeatAdjustmentButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SeatAdjustmentButtonLabel1, "-");
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButtonLabel1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButtonLabel1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatAdjustmentButtonLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatAdjustmentButtonLabel1, &ui_font_IBMPlexSansBold82, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatAdjustmentButton2 = lv_button_create(ui_SeatAdjustmentPanel);
    lv_obj_set_width(ui_SeatAdjustmentButton2, 320);
    lv_obj_set_height(ui_SeatAdjustmentButton2, 162);
    lv_obj_set_x(ui_SeatAdjustmentButton2, 0);
    lv_obj_set_y(ui_SeatAdjustmentButton2, -70);
    lv_obj_set_align(ui_SeatAdjustmentButton2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatAdjustmentButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatAdjustmentButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatAdjustmentButton2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatAdjustmentButton2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatAdjustmentButtonContainer2 = lv_obj_create(ui_SeatAdjustmentButton2);
    lv_obj_remove_style_all(ui_SeatAdjustmentButtonContainer2);
    lv_obj_set_width(ui_SeatAdjustmentButtonContainer2, 320);
    lv_obj_set_height(ui_SeatAdjustmentButtonContainer2, 110);
    lv_obj_set_align(ui_SeatAdjustmentButtonContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatAdjustmentButtonContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatAdjustmentButtonLabel2 = lv_label_create(ui_SeatAdjustmentButtonContainer2);
    lv_obj_set_width(ui_SeatAdjustmentButtonLabel2, 240);
    lv_obj_set_height(ui_SeatAdjustmentButtonLabel2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SeatAdjustmentButtonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SeatAdjustmentButtonLabel2, "+");
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButtonLabel2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButtonLabel2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatAdjustmentButtonLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatAdjustmentButtonLabel2, &ui_font_IBMPlexSansBold82, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatAdjustmentButton3 = lv_button_create(ui_SeatAdjustmentPanel);
    lv_obj_set_width(ui_SeatAdjustmentButton3, 205);
    lv_obj_set_height(ui_SeatAdjustmentButton3, 162);
    lv_obj_set_x(ui_SeatAdjustmentButton3, 0);
    lv_obj_set_y(ui_SeatAdjustmentButton3, -70);
    lv_obj_set_align(ui_SeatAdjustmentButton3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatAdjustmentButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatAdjustmentButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatAdjustmentButton3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatAdjustmentButton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatAdjustmentButtonContainer3 = lv_obj_create(ui_SeatAdjustmentButton3);
    lv_obj_remove_style_all(ui_SeatAdjustmentButtonContainer3);
    lv_obj_set_width(ui_SeatAdjustmentButtonContainer3, 320);
    lv_obj_set_height(ui_SeatAdjustmentButtonContainer3, 110);
    lv_obj_set_align(ui_SeatAdjustmentButtonContainer3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatAdjustmentButtonContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatAdjustmentButtonLabel3 = lv_label_create(ui_SeatAdjustmentButtonContainer3);
    lv_obj_set_width(ui_SeatAdjustmentButtonLabel3, 240);
    lv_obj_set_height(ui_SeatAdjustmentButtonLabel3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SeatAdjustmentButtonLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SeatAdjustmentButtonLabel3, "0°");
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButtonLabel3, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButtonLabel3, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatAdjustmentButtonLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatAdjustmentButtonLabel3, &ui_font_IBMPlexSansMedium53,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatAdjustmentButton4 = lv_button_create(ui_SeatAdjustmentPanel);
    lv_obj_set_width(ui_SeatAdjustmentButton4, 205);
    lv_obj_set_height(ui_SeatAdjustmentButton4, 162);
    lv_obj_set_x(ui_SeatAdjustmentButton4, 0);
    lv_obj_set_y(ui_SeatAdjustmentButton4, -70);
    lv_obj_set_align(ui_SeatAdjustmentButton4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatAdjustmentButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatAdjustmentButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatAdjustmentButton4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatAdjustmentButton4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatAdjustmentButtonContainer4 = lv_obj_create(ui_SeatAdjustmentButton4);
    lv_obj_remove_style_all(ui_SeatAdjustmentButtonContainer4);
    lv_obj_set_width(ui_SeatAdjustmentButtonContainer4, 320);
    lv_obj_set_height(ui_SeatAdjustmentButtonContainer4, 110);
    lv_obj_set_align(ui_SeatAdjustmentButtonContainer4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatAdjustmentButtonContainer4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatAdjustmentButtonLabel4 = lv_label_create(ui_SeatAdjustmentButtonContainer4);
    lv_obj_set_width(ui_SeatAdjustmentButtonLabel4, 240);
    lv_obj_set_height(ui_SeatAdjustmentButtonLabel4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SeatAdjustmentButtonLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SeatAdjustmentButtonLabel4, "15°");
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButtonLabel4, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButtonLabel4, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatAdjustmentButtonLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatAdjustmentButtonLabel4, &ui_font_IBMPlexSansMedium53,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatAdjustmentButton5 = lv_button_create(ui_SeatAdjustmentPanel);
    lv_obj_set_width(ui_SeatAdjustmentButton5, 205);
    lv_obj_set_height(ui_SeatAdjustmentButton5, 162);
    lv_obj_set_x(ui_SeatAdjustmentButton5, 0);
    lv_obj_set_y(ui_SeatAdjustmentButton5, -70);
    lv_obj_set_align(ui_SeatAdjustmentButton5, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SeatAdjustmentButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SeatAdjustmentButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeatAdjustmentButton5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_SeatAdjustmentButton5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SeatAdjustmentButtonContainer5 = lv_obj_create(ui_SeatAdjustmentButton5);
    lv_obj_remove_style_all(ui_SeatAdjustmentButtonContainer5);
    lv_obj_set_width(ui_SeatAdjustmentButtonContainer5, 320);
    lv_obj_set_height(ui_SeatAdjustmentButtonContainer5, 110);
    lv_obj_set_align(ui_SeatAdjustmentButtonContainer5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SeatAdjustmentButtonContainer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SeatAdjustmentButtonLabel5 = lv_label_create(ui_SeatAdjustmentButtonContainer5);
    lv_obj_set_width(ui_SeatAdjustmentButtonLabel5, 240);
    lv_obj_set_height(ui_SeatAdjustmentButtonLabel5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SeatAdjustmentButtonLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SeatAdjustmentButtonLabel5, "25°");
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButtonLabel5, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SeatAdjustmentButtonLabel5, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SeatAdjustmentButtonLabel5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SeatAdjustmentButtonLabel5, &ui_font_IBMPlexSansMedium53,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExitBarPushLeft = ui_ExitBarPushLeft_create(ui_SeatAdjustmentPanel);
    lv_obj_set_x(ui_ExitBarPushLeft, 0);
    lv_obj_set_y(ui_ExitBarPushLeft, -10);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0

    ui_ErrorWarningPanel1 = ui_ErrorWarningPanel_create(ui_SeatAdjustmentFlexScreen);
    lv_obj_set_x(ui_ErrorWarningPanel1, 0);
    lv_obj_set_y(ui_ErrorWarningPanel1, 180);

    ui_StatusPanel3 = ui_StatusPanel_create(ui_SeatAdjustmentFlexScreen);
    lv_obj_set_x(ui_StatusPanel3, 0);
    lv_obj_set_y(ui_StatusPanel3, 50);

}

void ui_SeatAdjustmentFlexScreen_screen_destroy(void)
{
    if(ui_SeatAdjustmentFlexScreen) lv_obj_del(ui_SeatAdjustmentFlexScreen);

    // NULL screen variables
    ui_SeatAdjustmentFlexScreen = NULL;
    ui_TopBar4 = NULL;
    ui_SeatAdjustmentScreenFlexPanel = NULL;
    ui_SeatFunctionsButtonsPanel = NULL;
    ui_SeatFunctionsLabel = NULL;
    ui_SeatButton1 = NULL;
    ui_SeatButtonContainer1 = NULL;
    ui_SeatButtonLabel1 = NULL;
    ui_SeatButtonValue1 = NULL;
    ui_SeatButton2 = NULL;
    ui_SeatButtonContainer2 = NULL;
    ui_SeatButtonLabel2 = NULL;
    ui_SeatButtonValue2 = NULL;
    ui_SeatButton3 = NULL;
    ui_SeatButtonContainer3 = NULL;
    ui_SeatButtonLabel3 = NULL;
    ui_SeatButtonValue3 = NULL;
    ui_SeatButton4 = NULL;
    ui_SeatButtonContainer4 = NULL;
    ui_SeatButtonLabel4 = NULL;
    ui_SeatButtonValue4 = NULL;
    ui_SeatButton5 = NULL;
    ui_SeatButtonContainer5 = NULL;
    ui_SeatButtonLabel5 = NULL;
    ui_SeatButton6 = NULL;
    ui_SeatButtonContainer6 = NULL;
    ui_SeatButtonLabel6 = NULL;
    ui_ExitBarPull1 = NULL;
    ui_SeatAdjustmentPanel = NULL;
    ui_AngleSettingLabel = NULL;
    ui_AngleIndicator = NULL;
    ui_AngleLabel = NULL;
    ui_MaxAngleLabel = NULL;
    ui_SeatAdjustmentButton1 = NULL;
    ui_SeatAdjustmentButtonContainer1 = NULL;
    ui_SeatAdjustmentButtonLabel1 = NULL;
    ui_SeatAdjustmentButton2 = NULL;
    ui_SeatAdjustmentButtonContainer2 = NULL;
    ui_SeatAdjustmentButtonLabel2 = NULL;
    ui_SeatAdjustmentButton3 = NULL;
    ui_SeatAdjustmentButtonContainer3 = NULL;
    ui_SeatAdjustmentButtonLabel3 = NULL;
    ui_SeatAdjustmentButton4 = NULL;
    ui_SeatAdjustmentButtonContainer4 = NULL;
    ui_SeatAdjustmentButtonLabel4 = NULL;
    ui_SeatAdjustmentButton5 = NULL;
    ui_SeatAdjustmentButtonContainer5 = NULL;
    ui_SeatAdjustmentButtonLabel5 = NULL;
    ui_ExitBarPushLeft = NULL;
    ui_ErrorWarningPanel1 = NULL;
    ui_StatusPanel3 = NULL;

}
