// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: pace-hmi-ui

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t *ui_SettingsScreen;
extern lv_obj_t *ui_AxesPanel;
extern lv_obj_t *ui_XBar;
extern lv_obj_t *ui_YBar;
extern lv_obj_t *ui_TwistBar;
extern void ui_event_SettingsButton2(lv_event_t *e);
extern lv_obj_t *ui_SettingsButton2;
extern lv_obj_t *ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
