// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

lv_obj_t * ui_UpdateScreen = NULL;
lv_obj_t * ui_TopBar11 = NULL;
lv_obj_t * ui_UpdatePanel = NULL;
lv_obj_t * ui_UpdatePanelInner = NULL;
lv_obj_t * ui_UpdateLabel = NULL;
lv_obj_t * ui_UpdateLog = NULL;
lv_obj_t * ui_UpdateProgressBar = NULL;
lv_obj_t * ui_UpdateProgressBarLabel = NULL;
lv_obj_t * ui_ErrorWarningPanel9 = NULL;
lv_obj_t * ui_StatusPanel10 = NULL;
// event funtions

// build funtions

void ui_UpdateScreen_screen_init(void)
{
    ui_UpdateScreen = lv_obj_create(NULL);
    lv_obj_set_scroll_snap_x(ui_UpdateScreen, LV_SCROLL_SNAP_CENTER);
    ui_object_set_themeable_style_property(ui_UpdateScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_UpdateScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_TopBar11 = ui_TopBar_create(ui_UpdateScreen);
    lv_obj_set_x(ui_TopBar11, 0);
    lv_obj_set_y(ui_TopBar11, 0);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0

    ui_UpdatePanel = lv_obj_create(ui_UpdateScreen);
    lv_obj_set_width(ui_UpdatePanel, lv_pct(100));
    lv_obj_set_height(ui_UpdatePanel, lv_pct(80));
    lv_obj_set_x(ui_UpdatePanel, 0);
    lv_obj_set_y(ui_UpdatePanel, 194);
    lv_obj_set_align(ui_UpdatePanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_UpdatePanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_UpdatePanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_UpdatePanel, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_UpdatePanel, LV_SCROLL_SNAP_START);
    ui_object_set_themeable_style_property(ui_UpdatePanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_UpdatePanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_side(ui_UpdatePanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpdatePanelInner = lv_obj_create(ui_UpdatePanel);
    lv_obj_set_width(ui_UpdatePanelInner, lv_pct(100));
    lv_obj_set_height(ui_UpdatePanelInner, lv_pct(100));
    lv_obj_set_align(ui_UpdatePanelInner, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_UpdatePanelInner, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_UpdatePanelInner, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_UpdatePanelInner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_UpdatePanelInner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_UpdatePanelInner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_UpdatePanelInner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_UpdatePanelInner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_pad_row(ui_UpdatePanelInner, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_UpdatePanelInner, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpdateLabel = lv_label_create(ui_UpdatePanelInner);
    lv_obj_set_width(ui_UpdateLabel, 660);
    lv_obj_set_height(ui_UpdateLabel, 50);
    lv_obj_set_align(ui_UpdateLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_UpdateLabel, "Update");
    ui_object_set_themeable_style_property(ui_UpdateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_UpdateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_UpdateLabel, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_UpdateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_UpdateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_UpdateLog = lv_textarea_create(ui_UpdatePanelInner);
    lv_obj_set_height(ui_UpdateLog, 800);
    lv_obj_set_width(ui_UpdateLog, lv_pct(100));
    lv_obj_set_align(ui_UpdateLog, LV_ALIGN_TOP_MID);
    lv_textarea_set_text(ui_UpdateLog,
                         "1AAAAAAAAAAAAA\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42");
    lv_textarea_set_placeholder_text(ui_UpdateLog, "Placeholder...");
    ui_object_set_themeable_style_property(ui_UpdateLog, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_UpdateLog, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_UpdateLog, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_UpdateLog, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_UpdateLog, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_UpdateLog, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_UpdateLog, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_UpdateLog, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);

    ui_UpdateProgressBar = lv_bar_create(ui_UpdatePanelInner);
    lv_bar_set_value(ui_UpdateProgressBar, 60, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_UpdateProgressBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_UpdateProgressBar, 600);
    lv_obj_set_height(ui_UpdateProgressBar, 60);
    lv_obj_set_x(ui_UpdateProgressBar, 0);
    lv_obj_set_y(ui_UpdateProgressBar, -20);
    lv_obj_set_align(ui_UpdateProgressBar, LV_ALIGN_BOTTOM_MID);
    ui_object_set_themeable_style_property(ui_UpdateProgressBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_UpdateProgressBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_object_set_themeable_style_property(ui_UpdateProgressBar, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_UpdateProgressBar, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_UpdateProgressBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_UpdateProgressBar,
                                                                                                        lv_obj_get_style_pad_right(ui_UpdateProgressBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_UpdateProgressBarLabel = lv_label_create(ui_UpdateProgressBar);
    lv_obj_set_width(ui_UpdateProgressBarLabel, 600);
    lv_obj_set_height(ui_UpdateProgressBarLabel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_UpdateProgressBarLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpdateProgressBarLabel, "Update: 70%");
    ui_object_set_themeable_style_property(ui_UpdateProgressBarLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_focused);
    ui_object_set_themeable_style_property(ui_UpdateProgressBarLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_focused);
    lv_obj_set_style_text_align(ui_UpdateProgressBarLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UpdateProgressBarLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ErrorWarningPanel9 = ui_ErrorWarningPanel_create(ui_UpdateScreen);
    lv_obj_set_x(ui_ErrorWarningPanel9, 0);
    lv_obj_set_y(ui_ErrorWarningPanel9, 180);

    ui_StatusPanel10 = ui_StatusPanel_create(ui_UpdateScreen);
    lv_obj_set_x(ui_StatusPanel10, 0);
    lv_obj_set_y(ui_StatusPanel10, 50);

}

void ui_UpdateScreen_screen_destroy(void)
{
    if(ui_UpdateScreen) lv_obj_del(ui_UpdateScreen);

    // NULL screen variables
    ui_UpdateScreen = NULL;
    ui_TopBar11 = NULL;
    ui_UpdatePanel = NULL;
    ui_UpdatePanelInner = NULL;
    ui_UpdateLabel = NULL;
    ui_UpdateLog = NULL;
    ui_UpdateProgressBar = NULL;
    ui_UpdateProgressBarLabel = NULL;
    ui_ErrorWarningPanel9 = NULL;
    ui_StatusPanel10 = NULL;

}
