// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui
//
// Excluded from import_ui.ps1's mirror - edited by hand, SquareLine's
// regenerated stubs for this file are ignored.
//
// flex_scroll_next / flex_scroll_previous went with the spec-V1 pager: there is
// no ui_FlexPanel to scroll and nothing in the export calls them. Spec V2
// navigates with the burger menu (main.cpp's nav_* section).

#include "ui.h"

// Still here for a CALL FUNCTION event in SquareLine to reach. Nothing in the
// current export wires one, so the theme is switched from the Skunk Works slot
// instead; main.cpp's rtps_poll_cb notices either way and saves the result.
void theme_toggle(lv_event_t * e)
{
    LV_UNUSED(e);
    _ui_switch_theme(ui_theme_idx == UI_THEME_DAY ? UI_THEME_DEFAULT : UI_THEME_DAY);
}
