// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

void ui_event_comp_ArrowsPanel_LeftArrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ArrowsPanel = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        flex_scroll_previous(e);
    }
}

void ui_event_comp_ArrowsPanel_RightArrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ArrowsPanel = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        flex_scroll_next(e);
    }
}

// COMPONENT ArrowsPanel

lv_obj_t * ui_ArrowsPanel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ArrowsPanel;
    cui_ArrowsPanel = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_ArrowsPanel, 720);
    lv_obj_set_height(cui_ArrowsPanel, 100);
    lv_obj_set_x(cui_ArrowsPanel, 0);
    lv_obj_set_y(cui_ArrowsPanel, -70);
    lv_obj_set_align(cui_ArrowsPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(cui_ArrowsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ArrowsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_ArrowsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ArrowsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_ArrowsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ArrowsPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t * cui_LeftArrow;
    cui_LeftArrow = lv_image_create(cui_ArrowsPanel);
    lv_image_set_src(cui_LeftArrow, &ui_img_arrow_left_png);
    lv_obj_set_width(cui_LeftArrow, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(cui_LeftArrow, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(cui_LeftArrow, -230);
    lv_obj_set_y(cui_LeftArrow, 0);
    lv_obj_set_align(cui_LeftArrow, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(cui_LeftArrow, 30);
    lv_obj_add_flag(cui_LeftArrow, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_LeftArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_LeftArrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_LeftArrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_text);

    lv_obj_t * cui_RightArrow;
    cui_RightArrow = lv_image_create(cui_ArrowsPanel);
    lv_image_set_src(cui_RightArrow, &ui_img_arrow_png);
    lv_obj_set_width(cui_RightArrow, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(cui_RightArrow, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(cui_RightArrow, 230);
    lv_obj_set_y(cui_RightArrow, 0);
    lv_obj_set_align(cui_RightArrow, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(cui_RightArrow, 30);
    lv_obj_add_flag(cui_RightArrow, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_RightArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_RightArrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_RightArrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_text);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_ARROWSPANEL_NUM);
    children[UI_COMP_ARROWSPANEL_ARROWSPANEL] = cui_ArrowsPanel;
    children[UI_COMP_ARROWSPANEL_LEFTARROW] = cui_LeftArrow;
    children[UI_COMP_ARROWSPANEL_RIGHTARROW] = cui_RightArrow;
    lv_obj_add_event_cb(cui_ArrowsPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ArrowsPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_LeftArrow, ui_event_comp_ArrowsPanel_LeftArrow, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_RightArrow, ui_event_comp_ArrowsPanel_RightArrow, LV_EVENT_ALL, children);
    ui_comp_ArrowsPanel_create_hook(cui_ArrowsPanel);
    return cui_ArrowsPanel;
}

