// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef _UI_COMP_MENUKEY_H
#define _UI_COMP_MENUKEY_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MenuKey
#define UI_COMP_MENUKEY_MENUKEY 0
#define UI_COMP_MENUKEY_GROUND 1
#define UI_COMP_MENUKEY_GROUND_BAR1 2
#define UI_COMP_MENUKEY_GROUND_BAR2 3
#define UI_COMP_MENUKEY_GROUND_BAR3 4
#define _UI_COMP_MENUKEY_NUM 5
lv_obj_t * ui_MenuKey_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
