// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

// COMPONENT NetRow

lv_obj_t * ui_NetRow_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_NetRow;
    cui_NetRow = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_NetRow, 720);
    lv_obj_set_height(cui_NetRow, 98);
    lv_obj_remove_flag(cui_NetRow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_NetRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_NetRow, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_NetRow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_NetRow, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_NetRow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_NetRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_NetRow, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_NetRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_NetRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_NetRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_NetRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_NetRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_NetRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_NetRowGround;
    cui_NetRowGround = lv_obj_create(cui_NetRow);
    lv_obj_set_width(cui_NetRowGround, 720);
    lv_obj_set_height(cui_NetRowGround, 96);
    lv_obj_remove_flag(cui_NetRowGround, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_NetRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_NetRowGround, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_NetRowGround, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_NetRowGround, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_NetRowGround, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(cui_NetRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_NetRowGround, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_NetRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_NetRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_NetRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_NetRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_NetRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_NetRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_NetRowGround, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_NetRowGround, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(cui_NetRowGround, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_NetRowGround, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    lv_obj_t * cui_NetRowName;
    cui_NetRowName = lv_label_create(cui_NetRowGround);
    lv_obj_set_width(cui_NetRowName, 460);
    lv_obj_set_height(cui_NetRowName, 44);
    lv_obj_set_x(cui_NetRowName, 30);
    lv_obj_set_y(cui_NetRowName, 33);
    lv_label_set_text(cui_NetRowName, "Network name");
    ui_object_set_themeable_style_property(cui_NetRowName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_NetRowName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_NetRowName, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_NetRowName, &ui_font_IBMPlexSansRegular34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_NetRowName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_NetRowName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_NetRowName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_NetRowName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_NetRowName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_NetRowName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_NetRowName, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_NetRowName, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_NetRowName, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_NetRowName, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t * cui_NetRowSignal;
    cui_NetRowSignal = lv_label_create(cui_NetRowGround);
    lv_obj_set_width(cui_NetRowSignal, 190);
    lv_obj_set_height(cui_NetRowSignal, 34);
    lv_obj_set_x(cui_NetRowSignal, 500);
    lv_obj_set_y(cui_NetRowSignal, 37);
    lv_label_set_text(cui_NetRowSignal, "-60 dBm");
    ui_object_set_themeable_style_property(cui_NetRowSignal, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_NetRowSignal, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_NetRowSignal, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_NetRowSignal, &ui_font_IBMPlexSansRegular24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_NetRowSignal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_NetRowSignal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_NetRowSignal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_NetRowSignal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_NetRowSignal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_NetRowSignal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_NetRowSignal, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_NetRowSignal, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_NetRowSignal, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_NetRowSignal, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_NETROW_NUM);
    children[UI_COMP_NETROW_NETROW] = cui_NetRow;
    children[UI_COMP_NETROW_NETROWGROUND] = cui_NetRowGround;
    children[UI_COMP_NETROW_NETROWGROUND_NETROWNAME] = cui_NetRowName;
    children[UI_COMP_NETROW_NETROWGROUND_NETROWSIGNAL] = cui_NetRowSignal;
    lv_obj_add_event_cb(cui_NetRow, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_NetRow, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_NetRow_create_hook(cui_NetRow);
    return cui_NetRow;
}

