// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef _UI_COMP_RELEASEROW_H
#define _UI_COMP_RELEASEROW_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ReleaseRow
#define UI_COMP_RELEASEROW_RELEASEROW 0
#define UI_COMP_RELEASEROW_RELEASEROWGROUND 1
#define UI_COMP_RELEASEROW_RELEASEROWGROUND_RELEASEROWTAG 2
#define UI_COMP_RELEASEROW_RELEASEROWGROUND_RELEASEROWNOTE 3
#define UI_COMP_RELEASEROW_RELEASEROWGROUND_RELEASEROWMARK 4
#define _UI_COMP_RELEASEROW_NUM 5
lv_obj_t * ui_ReleaseRow_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
