// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef _PACE_HMI_UI_UI_COMP_HOOK_H
#define _PACE_HMI_UI_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_DiagRow_create_hook(lv_obj_t * comp);
void ui_comp_DriveBand_create_hook(lv_obj_t * comp);
void ui_comp_ErrorBanner_create_hook(lv_obj_t * comp);
void ui_comp_MenuKey_create_hook(lv_obj_t * comp);
void ui_comp_MenuOverlay_create_hook(lv_obj_t * comp);
void ui_comp_SettingRow_create_hook(lv_obj_t * comp);
void ui_comp_SlotTile_create_hook(lv_obj_t * comp);
void ui_comp_TopBar_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
