// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef _UI_COMP_SLOTTILE_H
#define _UI_COMP_SLOTTILE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SlotTile
#define UI_COMP_SLOTTILE_SLOTTILE 0
#define UI_COMP_SLOTTILE_SLOTBOX 1
#define UI_COMP_SLOTTILE_SLOTBOX_SLOTTITLE 2
#define UI_COMP_SLOTTILE_SLOTBOX_SLOTSUBTITLE 3
#define _UI_COMP_SLOTTILE_NUM 4
lv_obj_t * ui_SlotTile_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
