// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef _UI_COMP_DIAGROW_H
#define _UI_COMP_DIAGROW_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT DiagRow
#define UI_COMP_DIAGROW_DIAGROW 0
#define UI_COMP_DIAGROW_DIAGHEAD 1
#define UI_COMP_DIAGROW_DIAGHEAD_DIAGNAMES 2
#define UI_COMP_DIAGROW_DIAGHEAD_DIAGNAMES_DIAGSHORT 3
#define UI_COMP_DIAGROW_DIAGHEAD_DIAGNAMES_DIAGLABEL 4
#define UI_COMP_DIAGROW_CELL1 5
#define UI_COMP_DIAGROW_CELL1_UNIT1 6
#define UI_COMP_DIAGROW_CELL1_VALUE1 7
#define UI_COMP_DIAGROW_CELL2 8
#define UI_COMP_DIAGROW_CELL2_UNIT2 9
#define UI_COMP_DIAGROW_CELL2_VALUE2 10
#define UI_COMP_DIAGROW_CELL3 11
#define UI_COMP_DIAGROW_CELL3_UNIT3 12
#define UI_COMP_DIAGROW_CELL3_VALUE3 13
#define _UI_COMP_DIAGROW_NUM 14
lv_obj_t * ui_DiagRow_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
