// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

// COMPONENT SettingRow

lv_obj_t * ui_SettingRow_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_SettingRow;
    cui_SettingRow = lv_button_create(comp_parent);
    lv_obj_set_width(cui_SettingRow, 700);
    lv_obj_set_height(cui_SettingRow, 98);
    lv_obj_set_x(cui_SettingRow, 0);
    lv_obj_set_y(cui_SettingRow, 100);
    lv_obj_set_align(cui_SettingRow, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_SettingRow, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_SettingRow, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_state(cui_SettingRow, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(cui_SettingRow, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_SettingRow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_SettingRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_SettingRow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_SettingRow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_SettingRow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_SettingRow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(cui_SettingRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_SettingRow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_SettingRow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_SettingRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_SettingRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_SettingRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_SettingRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_SettingRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_SettingRow, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_SettingRow, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_SettingRow, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(cui_SettingRow, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_focused);
    ui_object_set_themeable_style_property(cui_SettingRow, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_focused);

    lv_obj_t * cui_Head;
    cui_Head = lv_obj_create(cui_SettingRow);
    lv_obj_remove_style_all(cui_Head);
    lv_obj_set_width(cui_Head, 136);
    lv_obj_set_height(cui_Head, 98);
    lv_obj_set_align(cui_Head, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_Head, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(cui_Head, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Names;
    cui_Names = lv_obj_create(cui_Head);
    lv_obj_remove_style_all(cui_Names);
    lv_obj_set_height(cui_Names, 98);
    lv_obj_set_width(cui_Names, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(cui_Names, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Names, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Names, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_state(cui_Names, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(cui_Names, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Short;
    cui_Short = lv_label_create(cui_Names);
    lv_obj_set_width(cui_Short, 130);
    lv_obj_set_height(cui_Short, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_x(cui_Short, 20);
    lv_obj_set_y(cui_Short, 0);
    lv_label_set_long_mode(cui_Short, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(cui_Short, "M1");
    lv_obj_add_state(cui_Short, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(cui_Short, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_Short, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_Short, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Short, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Short, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_Short, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t * cui_Label;
    cui_Label = lv_label_create(cui_Names);
    lv_obj_set_width(cui_Label, 130);
    lv_obj_set_height(cui_Label, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_x(cui_Label, 20);
    lv_obj_set_y(cui_Label, 0);
    lv_obj_set_align(cui_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(cui_Label, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(cui_Label, "Tilt Left Motor");
    lv_obj_add_state(cui_Label, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_Label, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_Label, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t * cui_ValueBox;
    cui_ValueBox = lv_obj_create(cui_SettingRow);
    lv_obj_remove_style_all(cui_ValueBox);
    lv_obj_set_width(cui_ValueBox, 200);
    lv_obj_set_height(cui_ValueBox, 98);
    lv_obj_set_align(cui_ValueBox, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_ValueBox, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(cui_ValueBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Value;
    cui_Value = lv_label_create(cui_ValueBox);
    lv_obj_set_width(cui_Value, 200);
    lv_obj_set_height(cui_Value, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_align(cui_Value, LV_ALIGN_CENTER);
    lv_label_set_long_mode(cui_Value, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(cui_Value, "12.6");
    lv_obj_add_state(cui_Value, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(cui_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Value, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Value, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_Value, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t * cui_Minus;
    cui_Minus = lv_button_create(cui_SettingRow);
    lv_obj_set_width(cui_Minus, 132);
    lv_obj_set_height(cui_Minus, 86);
    lv_obj_set_x(cui_Minus, 0);
    lv_obj_set_y(cui_Minus, -70);
    lv_obj_set_align(cui_Minus, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_Minus, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(cui_Minus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Minus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Minus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Minus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_Minus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_Minus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_Minus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(cui_Minus, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Minus, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_Minus, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(cui_Minus, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_Minus, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t * cui_MinusBox;
    cui_MinusBox = lv_obj_create(cui_Minus);
    lv_obj_remove_style_all(cui_MinusBox);
    lv_obj_set_width(cui_MinusBox, 132);
    lv_obj_set_height(cui_MinusBox, 86);
    lv_obj_set_align(cui_MinusBox, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_MinusBox, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(cui_MinusBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_MinusLabel;
    cui_MinusLabel = lv_label_create(cui_MinusBox);
    lv_obj_set_width(cui_MinusLabel, 132);
    lv_obj_set_height(cui_MinusLabel, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(cui_MinusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MinusLabel, "-");
    lv_obj_add_state(cui_MinusLabel, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(cui_MinusLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_MinusLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_MinusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_MinusLabel, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_MinusLabel, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_MinusLabel, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t * cui_Plus;
    cui_Plus = lv_button_create(cui_SettingRow);
    lv_obj_set_width(cui_Plus, 132);
    lv_obj_set_height(cui_Plus, 86);
    lv_obj_set_x(cui_Plus, 0);
    lv_obj_set_y(cui_Plus, -70);
    lv_obj_set_align(cui_Plus, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_Plus, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(cui_Plus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Plus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Plus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Plus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_Plus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_Plus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_Plus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(cui_Plus, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_Plus, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_Plus, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(cui_Plus, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_Plus, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t * cui_PlusBox;
    cui_PlusBox = lv_obj_create(cui_Plus);
    lv_obj_remove_style_all(cui_PlusBox);
    lv_obj_set_width(cui_PlusBox, 132);
    lv_obj_set_height(cui_PlusBox, 86);
    lv_obj_set_align(cui_PlusBox, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_PlusBox, LV_STATE_FOCUSED);       /// States
    lv_obj_remove_flag(cui_PlusBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_PlusLabel;
    cui_PlusLabel = lv_label_create(cui_PlusBox);
    lv_obj_set_width(cui_PlusLabel, 132);
    lv_obj_set_height(cui_PlusLabel, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(cui_PlusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_PlusLabel, "+");
    lv_obj_add_state(cui_PlusLabel, LV_STATE_FOCUSED);       /// States
    ui_object_set_themeable_style_property(cui_PlusLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_PlusLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_PlusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_PlusLabel, &ui_font_IBMPlexSansMedium53, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_PlusLabel, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_PlusLabel, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SETTINGROW_NUM);
    children[UI_COMP_SETTINGROW_SETTINGROW] = cui_SettingRow;
    children[UI_COMP_SETTINGROW_HEAD] = cui_Head;
    children[UI_COMP_SETTINGROW_HEAD_NAMES] = cui_Names;
    children[UI_COMP_SETTINGROW_HEAD_NAMES_SHORT] = cui_Short;
    children[UI_COMP_SETTINGROW_HEAD_NAMES_LABEL] = cui_Label;
    children[UI_COMP_SETTINGROW_VALUEBOX] = cui_ValueBox;
    children[UI_COMP_SETTINGROW_VALUEBOX_VALUE] = cui_Value;
    children[UI_COMP_SETTINGROW_MINUS] = cui_Minus;
    children[UI_COMP_SETTINGROW_MINUS_MINUSBOX] = cui_MinusBox;
    children[UI_COMP_SETTINGROW_MINUS_MINUSBOX_MINUSLABEL] = cui_MinusLabel;
    children[UI_COMP_SETTINGROW_PLUS] = cui_Plus;
    children[UI_COMP_SETTINGROW_PLUS_PLUSBOX] = cui_PlusBox;
    children[UI_COMP_SETTINGROW_PLUS_PLUSBOX_PLUSLABEL] = cui_PlusLabel;
    lv_obj_add_event_cb(cui_SettingRow, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_SettingRow, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_SettingRow_create_hook(cui_SettingRow);
    return cui_SettingRow;
}

