// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef _UI_COMP_SETTINGROW_H
#define _UI_COMP_SETTINGROW_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SettingRow
#define UI_COMP_SETTINGROW_SETTINGROW 0
#define UI_COMP_SETTINGROW_HEAD 1
#define UI_COMP_SETTINGROW_HEAD_NAMES 2
#define UI_COMP_SETTINGROW_HEAD_NAMES_SHORT 3
#define UI_COMP_SETTINGROW_HEAD_NAMES_LABEL 4
#define UI_COMP_SETTINGROW_VALUEBOX 5
#define UI_COMP_SETTINGROW_VALUEBOX_VALUE 6
#define UI_COMP_SETTINGROW_MINUS 7
#define UI_COMP_SETTINGROW_MINUS_MINUSBOX 8
#define UI_COMP_SETTINGROW_MINUS_MINUSBOX_MINUSLABEL 9
#define UI_COMP_SETTINGROW_PLUS 10
#define UI_COMP_SETTINGROW_PLUS_PLUSBOX 11
#define UI_COMP_SETTINGROW_PLUS_PLUSBOX_PLUSLABEL 12
#define _UI_COMP_SETTINGROW_NUM 13
lv_obj_t * ui_SettingRow_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
