// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

// COMPONENT ReleaseRow

lv_obj_t * ui_ReleaseRow_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ReleaseRow;
    cui_ReleaseRow = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_ReleaseRow, 720);
    lv_obj_set_height(cui_ReleaseRow, 110);
    lv_obj_remove_flag(cui_ReleaseRow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ReleaseRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ReleaseRow, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ReleaseRow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ReleaseRow, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ReleaseRow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_ReleaseRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_ReleaseRow, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ReleaseRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ReleaseRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ReleaseRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ReleaseRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_ReleaseRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ReleaseRow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ReleaseRowGround;
    cui_ReleaseRowGround = lv_obj_create(cui_ReleaseRow);
    lv_obj_set_width(cui_ReleaseRowGround, 720);
    lv_obj_set_height(cui_ReleaseRowGround, 108);
    lv_obj_remove_flag(cui_ReleaseRowGround, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ReleaseRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_ReleaseRowGround, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowGround, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowGround, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowGround, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(cui_ReleaseRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_ReleaseRowGround, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ReleaseRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ReleaseRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ReleaseRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ReleaseRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_ReleaseRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ReleaseRowGround, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_ReleaseRowGround, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_ReleaseRowGround, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(cui_ReleaseRowGround, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_ReleaseRowGround, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    lv_obj_t * cui_ReleaseRowTag;
    cui_ReleaseRowTag = lv_label_create(cui_ReleaseRowGround);
    lv_obj_set_width(cui_ReleaseRowTag, 440);
    lv_obj_set_height(cui_ReleaseRowTag, 44);
    lv_obj_set_x(cui_ReleaseRowTag, 30);
    lv_obj_set_y(cui_ReleaseRowTag, 17);
    lv_label_set_text(cui_ReleaseRowTag, "v0.0.0");
    ui_object_set_themeable_style_property(cui_ReleaseRowTag, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_ReleaseRowTag, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_ReleaseRowTag, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_ReleaseRowTag, &ui_font_IBMPlexSansRegular34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ReleaseRowTag, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ReleaseRowTag, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ReleaseRowTag, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ReleaseRowTag, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_ReleaseRowTag, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ReleaseRowTag, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_ReleaseRowTag, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowTag, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowTag, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowTag, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t * cui_ReleaseRowNote;
    cui_ReleaseRowNote = lv_label_create(cui_ReleaseRowGround);
    lv_obj_set_width(cui_ReleaseRowNote, 440);
    lv_obj_set_height(cui_ReleaseRowNote, 32);
    lv_obj_set_x(cui_ReleaseRowNote, 30);
    lv_obj_set_y(cui_ReleaseRowNote, 65);
    lv_label_set_text(cui_ReleaseRowNote, "Pre-release, 1 Jan 2026");
    ui_object_set_themeable_style_property(cui_ReleaseRowNote, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(cui_ReleaseRowNote, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_align(cui_ReleaseRowNote, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_ReleaseRowNote, &ui_font_IBMPlexSansRegular24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ReleaseRowNote, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ReleaseRowNote, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ReleaseRowNote, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ReleaseRowNote, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_ReleaseRowNote, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ReleaseRowNote, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_ReleaseRowNote, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowNote, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowNote, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowNote, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t * cui_ReleaseRowMark;
    cui_ReleaseRowMark = lv_label_create(cui_ReleaseRowGround);
    lv_obj_set_width(cui_ReleaseRowMark, 210);
    lv_obj_set_height(cui_ReleaseRowMark, 34);
    lv_obj_set_x(cui_ReleaseRowMark, 480);
    lv_obj_set_y(cui_ReleaseRowMark, 39);
    lv_label_set_text(cui_ReleaseRowMark, "Installed");
    ui_object_set_themeable_style_property(cui_ReleaseRowMark, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_ReleaseRowMark, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(cui_ReleaseRowMark, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_ReleaseRowMark, &ui_font_IBMPlexSansRegular24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ReleaseRowMark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ReleaseRowMark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ReleaseRowMark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ReleaseRowMark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_ReleaseRowMark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ReleaseRowMark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_ReleaseRowMark, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowMark, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowMark, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ReleaseRowMark, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_RELEASEROW_NUM);
    children[UI_COMP_RELEASEROW_RELEASEROW] = cui_ReleaseRow;
    children[UI_COMP_RELEASEROW_RELEASEROWGROUND] = cui_ReleaseRowGround;
    children[UI_COMP_RELEASEROW_RELEASEROWGROUND_RELEASEROWTAG] = cui_ReleaseRowTag;
    children[UI_COMP_RELEASEROW_RELEASEROWGROUND_RELEASEROWNOTE] = cui_ReleaseRowNote;
    children[UI_COMP_RELEASEROW_RELEASEROWGROUND_RELEASEROWMARK] = cui_ReleaseRowMark;
    lv_obj_add_event_cb(cui_ReleaseRow, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ReleaseRow, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ReleaseRow_create_hook(cui_ReleaseRow);
    return cui_ReleaseRow;
}

