// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

// COMPONENT ErrorBanner

lv_obj_t * ui_ErrorBanner_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ErrorBanner;
    cui_ErrorBanner = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_ErrorBanner, 720);
    lv_obj_set_height(cui_ErrorBanner, 400);
    lv_obj_set_x(cui_ErrorBanner, 0);
    lv_obj_set_y(cui_ErrorBanner, 195);
    lv_obj_add_flag(cui_ErrorBanner, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(cui_ErrorBanner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ErrorBanner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_ErrorBanner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ErrorBanner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_ErrorBanner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_ErrorBanner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(cui_ErrorBanner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_ErrorBanner, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ErrorBanner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ErrorBanner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ErrorBanner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ErrorBanner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_ErrorBanner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ErrorBanner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BannerTitle;
    cui_BannerTitle = lv_label_create(cui_ErrorBanner);
    lv_obj_set_width(cui_BannerTitle, 660);
    lv_obj_set_height(cui_BannerTitle, 40);
    lv_obj_set_x(cui_BannerTitle, 30);
    lv_obj_set_y(cui_BannerTitle, 55);
    lv_label_set_text(cui_BannerTitle, "ERROR TYPE");
    ui_object_set_themeable_style_property(cui_BannerTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_alert);
    ui_object_set_themeable_style_property(cui_BannerTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_alert);
    lv_obj_set_style_text_font(cui_BannerTitle, &ui_font_MontserratSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_BannerTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_BannerTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_BannerTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_BannerTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_BannerTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_BannerTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BannerBox;
    cui_BannerBox = lv_obj_create(cui_ErrorBanner);
    lv_obj_remove_style_all(cui_BannerBox);
    lv_obj_set_width(cui_BannerBox, 660);
    lv_obj_set_height(cui_BannerBox, 260);
    lv_obj_set_x(cui_BannerBox, 30);
    lv_obj_set_y(cui_BannerBox, 110);
    lv_obj_remove_flag(cui_BannerBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(cui_BannerBox, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_BannerBox, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(cui_BannerBox, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_BannerBox, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(cui_BannerBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_BannerBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_BannerBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_BannerBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_BannerBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_BannerBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_BannerBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BannerMessage;
    cui_BannerMessage = lv_label_create(cui_BannerBox);
    lv_obj_set_width(cui_BannerMessage, 660);
    lv_obj_set_height(cui_BannerMessage, 120);
    lv_label_set_text(cui_BannerMessage, "BODY OF TEST MESSAGE RECEIVED VIA RTPS");
    ui_object_set_themeable_style_property(cui_BannerMessage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(cui_BannerMessage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(cui_BannerMessage, &ui_font_MontserratSemiBold44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_BannerMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_BannerMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_BannerMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_BannerMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_BannerMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_BannerMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BannerFooter;
    cui_BannerFooter = lv_label_create(cui_BannerBox);
    lv_obj_set_width(cui_BannerFooter, 660);
    lv_obj_set_height(cui_BannerFooter, 120);
    lv_obj_set_x(cui_BannerFooter, 0);
    lv_obj_set_y(cui_BannerFooter, 130);
    lv_label_set_text(cui_BannerFooter, "FOOTER RECEIVED VIA RTPS");
    ui_object_set_themeable_style_property(cui_BannerFooter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(cui_BannerFooter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(cui_BannerFooter, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_BannerFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_BannerFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_BannerFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_BannerFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_BannerFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_BannerFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_ERRORBANNER_NUM);
    children[UI_COMP_ERRORBANNER_ERRORBANNER] = cui_ErrorBanner;
    children[UI_COMP_ERRORBANNER_BANNERTITLE] = cui_BannerTitle;
    children[UI_COMP_ERRORBANNER_BANNERBOX] = cui_BannerBox;
    children[UI_COMP_ERRORBANNER_BANNERBOX_BANNERMESSAGE] = cui_BannerMessage;
    children[UI_COMP_ERRORBANNER_BANNERBOX_BANNERFOOTER] = cui_BannerFooter;
    lv_obj_add_event_cb(cui_ErrorBanner, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ErrorBanner, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ErrorBanner_create_hook(cui_ErrorBanner);
    return cui_ErrorBanner;
}

