// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

lv_obj_t * ui_InternetScreen = NULL;
lv_obj_t * ui_InternetBody = NULL;
lv_obj_t * ui_InternetTitle = NULL;
lv_obj_t * ui_InternetContent = NULL;
lv_obj_t * ui_NetConnectionEyebrow = NULL;
lv_obj_t * ui_NetChoiceEthernet = NULL;
lv_obj_t * ui_NetChoiceEthernetLabel = NULL;
lv_obj_t * ui_NetChoiceWifi = NULL;
lv_obj_t * ui_NetChoiceWifiLabel = NULL;
lv_obj_t * ui_NetWifiEyebrow = NULL;
lv_obj_t * ui_NetWifiButton = NULL;
lv_obj_t * ui_NetWifiName = NULL;
lv_obj_t * ui_NetWifiChevron = NULL;
lv_obj_t * ui_NetStatusEyebrow = NULL;
lv_obj_t * ui_NetUsingKey = NULL;
lv_obj_t * ui_NetUsingValue = NULL;
lv_obj_t * ui_NetStateKey = NULL;
lv_obj_t * ui_NetStateValue = NULL;
lv_obj_t * ui_NetIpKey = NULL;
lv_obj_t * ui_NetIpValue = NULL;
lv_obj_t * ui_NetSignalKey = NULL;
lv_obj_t * ui_NetSignalValue = NULL;
lv_obj_t * ui_NetRestartButton = NULL;
lv_obj_t * ui_NetRestartButtonLabel = NULL;
lv_obj_t * ui_NetPickPanel = NULL;
lv_obj_t * ui_NetPickBack = NULL;
lv_obj_t * ui_NetPickBackLabel = NULL;
lv_obj_t * ui_NetPickTitle = NULL;
lv_obj_t * ui_NetPickStatus = NULL;
lv_obj_t * ui_NetList = NULL;
lv_obj_t * ui_NetRowTemplate = NULL;
lv_obj_t * ui_NetPwPanel = NULL;
lv_obj_t * ui_NetPwBack = NULL;
lv_obj_t * ui_NetPwBackLabel = NULL;
lv_obj_t * ui_NetPwTitle = NULL;
lv_obj_t * ui_NetPwEyebrow = NULL;
lv_obj_t * ui_NetPwBox = NULL;
lv_obj_t * ui_NetPwStatus = NULL;
lv_obj_t * ui_NetPwKeyboard = NULL;
lv_obj_t * ui_TopBar12 = NULL;
lv_obj_t * ui_DriveBand12 = NULL;
lv_obj_t * ui_ErrorBanner12 = NULL;
lv_obj_t * ui_MenuKey12 = NULL;
lv_obj_t * ui_MenuOverlay12 = NULL;
// event funtions

// build funtions

void ui_InternetScreen_screen_init(void)
{
    ui_InternetScreen = lv_obj_create(NULL);
    ui_object_set_themeable_style_property(ui_InternetScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_InternetScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_InternetBody = lv_obj_create(ui_InternetScreen);
    lv_obj_set_width(ui_InternetBody, 720);
    lv_obj_set_height(ui_InternetBody, 921);
    lv_obj_set_x(ui_InternetBody, 0);
    lv_obj_set_y(ui_InternetBody, 195);
    lv_obj_set_flex_flow(ui_InternetBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_InternetBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_InternetBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_InternetBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_InternetBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_InternetBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_InternetBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_InternetBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_InternetBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_InternetBody, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_InternetBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_InternetBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_InternetBody, 52, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_InternetBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_InternetBody, 34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_InternetBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InternetTitle = lv_label_create(ui_InternetBody);
    lv_obj_set_width(ui_InternetTitle, 720);
    lv_obj_set_height(ui_InternetTitle, 47);
    lv_obj_set_x(ui_InternetTitle, 0);
    lv_obj_set_y(ui_InternetTitle, -7);
    lv_label_set_text(ui_InternetTitle, "Internet Settings");
    ui_object_set_themeable_style_property(ui_InternetTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_InternetTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_InternetTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InternetTitle, &ui_font_MontserratSemiBold44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_InternetTitle, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_InternetTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_InternetTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_InternetTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_InternetTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_InternetTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InternetContent = lv_obj_create(ui_InternetBody);
    lv_obj_set_width(ui_InternetContent, 720);
    lv_obj_set_height(ui_InternetContent, 788);
    lv_obj_remove_flag(ui_InternetContent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_InternetContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_InternetContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_InternetContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_InternetContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_InternetContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_InternetContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_InternetContent, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_InternetContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_InternetContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_InternetContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_InternetContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_InternetContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_InternetContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetConnectionEyebrow = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetConnectionEyebrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetConnectionEyebrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetConnectionEyebrow, 30);
    lv_obj_set_y(ui_NetConnectionEyebrow, 8);
    lv_label_set_text(ui_NetConnectionEyebrow, "CONNECTION");
    ui_object_set_themeable_style_property(ui_NetConnectionEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_NetConnectionEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_NetConnectionEyebrow, &ui_font_MontserratSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetConnectionEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetConnectionEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetConnectionEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetConnectionEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetConnectionEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetConnectionEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetChoiceEthernet = lv_button_create(ui_InternetContent);
    lv_obj_set_width(ui_NetChoiceEthernet, 320);
    lv_obj_set_height(ui_NetChoiceEthernet, 162);
    lv_obj_set_x(ui_NetChoiceEthernet, 30);
    lv_obj_set_y(ui_NetChoiceEthernet, 48);
    lv_obj_add_flag(ui_NetChoiceEthernet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_NetChoiceEthernet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NetChoiceEthernet, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernet, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernet, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_NetChoiceEthernet, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NetChoiceEthernet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NetChoiceEthernet, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetChoiceEthernet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetChoiceEthernet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetChoiceEthernet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetChoiceEthernet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetChoiceEthernet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetChoiceEthernet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernet, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernet, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernet, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernet, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    ui_NetChoiceEthernetLabel = lv_label_create(ui_NetChoiceEthernet);
    lv_obj_set_width(ui_NetChoiceEthernetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetChoiceEthernetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetChoiceEthernetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetChoiceEthernetLabel, "Ethernet");
    ui_object_set_themeable_style_property(ui_NetChoiceEthernetLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernetLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_NetChoiceEthernetLabel, &ui_font_MontserratSemiBold44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetChoiceEthernetLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetChoiceEthernetLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetChoiceEthernetLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetChoiceEthernetLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetChoiceEthernetLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetChoiceEthernetLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernetLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernetLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernetLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetChoiceEthernetLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_NetChoiceWifi = lv_button_create(ui_InternetContent);
    lv_obj_set_width(ui_NetChoiceWifi, 320);
    lv_obj_set_height(ui_NetChoiceWifi, 162);
    lv_obj_set_x(ui_NetChoiceWifi, 370);
    lv_obj_set_y(ui_NetChoiceWifi, 48);
    lv_obj_add_flag(ui_NetChoiceWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_NetChoiceWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NetChoiceWifi, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetChoiceWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetChoiceWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_NetChoiceWifi, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NetChoiceWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NetChoiceWifi, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetChoiceWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetChoiceWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetChoiceWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetChoiceWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetChoiceWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetChoiceWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetChoiceWifi, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetChoiceWifi, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_NetChoiceWifi, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetChoiceWifi, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    ui_NetChoiceWifiLabel = lv_label_create(ui_NetChoiceWifi);
    lv_obj_set_width(ui_NetChoiceWifiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetChoiceWifiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetChoiceWifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetChoiceWifiLabel, "WiFi");
    ui_object_set_themeable_style_property(ui_NetChoiceWifiLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetChoiceWifiLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_NetChoiceWifiLabel, &ui_font_MontserratSemiBold44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetChoiceWifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetChoiceWifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetChoiceWifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetChoiceWifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetChoiceWifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetChoiceWifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetChoiceWifiLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetChoiceWifiLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetChoiceWifiLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetChoiceWifiLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_NetWifiEyebrow = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetWifiEyebrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetWifiEyebrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetWifiEyebrow, 30);
    lv_obj_set_y(ui_NetWifiEyebrow, 236);
    lv_label_set_text(ui_NetWifiEyebrow, "WIFI NETWORK");
    ui_object_set_themeable_style_property(ui_NetWifiEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_NetWifiEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_NetWifiEyebrow, &ui_font_MontserratSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetWifiEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetWifiEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetWifiEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetWifiEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetWifiEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetWifiEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetWifiButton = lv_button_create(ui_InternetContent);
    lv_obj_set_width(ui_NetWifiButton, 660);
    lv_obj_set_height(ui_NetWifiButton, 116);
    lv_obj_set_x(ui_NetWifiButton, 30);
    lv_obj_set_y(ui_NetWifiButton, 276);
    lv_obj_add_flag(ui_NetWifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_NetWifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NetWifiButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetWifiButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetWifiButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_NetWifiButton, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NetWifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NetWifiButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetWifiButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetWifiButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_NetWifiButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetWifiButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    ui_NetWifiName = lv_label_create(ui_NetWifiButton);
    lv_obj_set_width(ui_NetWifiName, 520);
    lv_obj_set_height(ui_NetWifiName, 44);
    lv_obj_set_x(ui_NetWifiName, 24);
    lv_obj_set_y(ui_NetWifiName, 39);
    lv_label_set_text(ui_NetWifiName, "Not set");
    ui_object_set_themeable_style_property(ui_NetWifiName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetWifiName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_NetWifiName, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetWifiName, &ui_font_IBMPlexSansRegular34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetWifiName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetWifiName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetWifiName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetWifiName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetWifiName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetWifiName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetWifiName, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetWifiName, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetWifiName, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetWifiName, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_NetWifiChevron = lv_label_create(ui_NetWifiButton);
    lv_obj_set_width(ui_NetWifiChevron, 76);
    lv_obj_set_height(ui_NetWifiChevron, 60);
    lv_obj_set_x(ui_NetWifiChevron, 560);
    lv_obj_set_y(ui_NetWifiChevron, 29);
    lv_label_set_text(ui_NetWifiChevron, "");
    ui_object_set_themeable_style_property(ui_NetWifiChevron, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetWifiChevron, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_NetWifiChevron, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetWifiChevron, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetWifiChevron, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetWifiChevron, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetWifiChevron, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetWifiChevron, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetWifiChevron, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetWifiChevron, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetWifiChevron, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetWifiChevron, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetWifiChevron, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetWifiChevron, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_NetStatusEyebrow = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetStatusEyebrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetStatusEyebrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetStatusEyebrow, 30);
    lv_obj_set_y(ui_NetStatusEyebrow, 418);
    lv_label_set_text(ui_NetStatusEyebrow, "STATUS");
    ui_object_set_themeable_style_property(ui_NetStatusEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_NetStatusEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_NetStatusEyebrow, &ui_font_MontserratSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetStatusEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetStatusEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetStatusEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetStatusEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetStatusEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetStatusEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetUsingKey = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetUsingKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetUsingKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetUsingKey, 30);
    lv_obj_set_y(ui_NetUsingKey, 458);
    lv_label_set_text(ui_NetUsingKey, "Using");
    ui_object_set_themeable_style_property(ui_NetUsingKey, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_NetUsingKey, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_NetUsingKey, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetUsingKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetUsingKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetUsingKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetUsingKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetUsingKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetUsingKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetUsingValue = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetUsingValue, 440);
    lv_obj_set_height(ui_NetUsingValue, 36);
    lv_obj_set_x(ui_NetUsingValue, 250);
    lv_obj_set_y(ui_NetUsingValue, 458);
    lv_label_set_text(ui_NetUsingValue, "--");
    ui_object_set_themeable_style_property(ui_NetUsingValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetUsingValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_NetUsingValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetUsingValue, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetUsingValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetUsingValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetUsingValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetUsingValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetUsingValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetUsingValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetStateKey = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetStateKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetStateKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetStateKey, 30);
    lv_obj_set_y(ui_NetStateKey, 498);
    lv_label_set_text(ui_NetStateKey, "State");
    ui_object_set_themeable_style_property(ui_NetStateKey, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_NetStateKey, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_NetStateKey, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetStateKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetStateKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetStateKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetStateKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetStateKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetStateKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetStateValue = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetStateValue, 440);
    lv_obj_set_height(ui_NetStateValue, 36);
    lv_obj_set_x(ui_NetStateValue, 250);
    lv_obj_set_y(ui_NetStateValue, 498);
    lv_label_set_text(ui_NetStateValue, "--");
    ui_object_set_themeable_style_property(ui_NetStateValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetStateValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_NetStateValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetStateValue, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetStateValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetStateValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetStateValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetStateValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetStateValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetStateValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetIpKey = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetIpKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetIpKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetIpKey, 30);
    lv_obj_set_y(ui_NetIpKey, 538);
    lv_label_set_text(ui_NetIpKey, "IP address");
    ui_object_set_themeable_style_property(ui_NetIpKey, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_NetIpKey, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_NetIpKey, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetIpKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetIpKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetIpKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetIpKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetIpKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetIpKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetIpValue = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetIpValue, 440);
    lv_obj_set_height(ui_NetIpValue, 36);
    lv_obj_set_x(ui_NetIpValue, 250);
    lv_obj_set_y(ui_NetIpValue, 538);
    lv_label_set_text(ui_NetIpValue, "--");
    ui_object_set_themeable_style_property(ui_NetIpValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetIpValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_NetIpValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetIpValue, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetIpValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetIpValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetIpValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetIpValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetIpValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetIpValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetSignalKey = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetSignalKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetSignalKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetSignalKey, 30);
    lv_obj_set_y(ui_NetSignalKey, 578);
    lv_label_set_text(ui_NetSignalKey, "Signal");
    ui_object_set_themeable_style_property(ui_NetSignalKey, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_NetSignalKey, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_NetSignalKey, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetSignalKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetSignalKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetSignalKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetSignalKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetSignalKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetSignalKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetSignalValue = lv_label_create(ui_InternetContent);
    lv_obj_set_width(ui_NetSignalValue, 440);
    lv_obj_set_height(ui_NetSignalValue, 36);
    lv_obj_set_x(ui_NetSignalValue, 250);
    lv_obj_set_y(ui_NetSignalValue, 578);
    lv_label_set_text(ui_NetSignalValue, "--");
    ui_object_set_themeable_style_property(ui_NetSignalValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetSignalValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_NetSignalValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetSignalValue, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetSignalValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetSignalValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetSignalValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetSignalValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetSignalValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetSignalValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetRestartButton = lv_button_create(ui_InternetContent);
    lv_obj_set_width(ui_NetRestartButton, 660);
    lv_obj_set_height(ui_NetRestartButton, 116);
    lv_obj_set_x(ui_NetRestartButton, 30);
    lv_obj_set_y(ui_NetRestartButton, 638);
    lv_obj_add_flag(ui_NetRestartButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_NetRestartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NetRestartButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetRestartButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetRestartButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetRestartButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetRestartButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_NetRestartButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetRestartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetRestartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetRestartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetRestartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetRestartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetRestartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetRestartButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetRestartButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_NetRestartButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetRestartButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    ui_NetRestartButtonLabel = lv_label_create(ui_NetRestartButton);
    lv_obj_set_width(ui_NetRestartButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetRestartButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetRestartButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetRestartButtonLabel, "Restart to apply");
    ui_object_set_themeable_style_property(ui_NetRestartButtonLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetRestartButtonLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_NetRestartButtonLabel, &ui_font_MontserratSemiBold44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetRestartButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetRestartButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetRestartButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetRestartButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetRestartButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetRestartButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetRestartButtonLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetRestartButtonLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetRestartButtonLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetRestartButtonLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_NetPickPanel = lv_obj_create(ui_InternetScreen);
    lv_obj_set_width(ui_NetPickPanel, 720);
    lv_obj_set_height(ui_NetPickPanel, 921);
    lv_obj_set_x(ui_NetPickPanel, 0);
    lv_obj_set_y(ui_NetPickPanel, 195);
    lv_obj_add_flag(ui_NetPickPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_NetPickPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_NetPickPanel, LV_DIR_VER);
    lv_obj_set_style_radius(ui_NetPickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetPickPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPickPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetPickPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPickPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_NetPickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_NetPickPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetPickBack = lv_button_create(ui_NetPickPanel);
    lv_obj_set_width(ui_NetPickBack, 116);
    lv_obj_set_height(ui_NetPickBack, 116);
    lv_obj_set_x(ui_NetPickBack, 30);
    lv_obj_set_y(ui_NetPickBack, 50);
    lv_obj_add_flag(ui_NetPickBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_NetPickBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NetPickBack, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetPickBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPickBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_NetPickBack, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NetPickBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NetPickBack, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPickBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPickBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPickBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPickBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPickBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPickBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetPickBack, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetPickBack, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_NetPickBack, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetPickBack, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    ui_NetPickBackLabel = lv_label_create(ui_NetPickBack);
    lv_obj_set_width(ui_NetPickBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetPickBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetPickBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetPickBackLabel, "");
    ui_object_set_themeable_style_property(ui_NetPickBackLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetPickBackLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_NetPickBackLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPickBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPickBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPickBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPickBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPickBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPickBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetPickBackLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPickBackLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetPickBackLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPickBackLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_NetPickTitle = lv_label_create(ui_NetPickPanel);
    lv_obj_set_width(ui_NetPickTitle, 480);
    lv_obj_set_height(ui_NetPickTitle, 50);
    lv_obj_set_x(ui_NetPickTitle, 176);
    lv_obj_set_y(ui_NetPickTitle, 85);
    lv_label_set_text(ui_NetPickTitle, "Choose network");
    ui_object_set_themeable_style_property(ui_NetPickTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetPickTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_NetPickTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetPickTitle, &ui_font_MontserratSemiBold44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetPickStatus = lv_label_create(ui_NetPickPanel);
    lv_obj_set_width(ui_NetPickStatus, 660);
    lv_obj_set_height(ui_NetPickStatus, 36);
    lv_obj_set_x(ui_NetPickStatus, 30);
    lv_obj_set_y(ui_NetPickStatus, 189);
    lv_label_set_text(ui_NetPickStatus, "Scanning...");
    ui_object_set_themeable_style_property(ui_NetPickStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_NetPickStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_align(ui_NetPickStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetPickStatus, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPickStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPickStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPickStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPickStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPickStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPickStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetList = lv_obj_create(ui_NetPickPanel);
    lv_obj_set_width(ui_NetList, 720);
    lv_obj_set_height(ui_NetList, 682);
    lv_obj_set_x(ui_NetList, 0);
    lv_obj_set_y(ui_NetList, 239);
    lv_obj_set_flex_flow(ui_NetList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_NetList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_NetList, LV_DIR_VER);
    lv_obj_set_style_radius(ui_NetList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetList, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetList, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetList, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetList, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_NetList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_NetList, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetRowTemplate = ui_NetRow_create(ui_NetList);
    lv_obj_set_width(ui_NetRowTemplate, 720);
    lv_obj_set_height(ui_NetRowTemplate, 98);
    lv_obj_set_x(ui_NetRowTemplate, 0);
    lv_obj_set_y(ui_NetRowTemplate, 0);

    ui_NetPwPanel = lv_obj_create(ui_InternetScreen);
    lv_obj_set_width(ui_NetPwPanel, 720);
    lv_obj_set_height(ui_NetPwPanel, 921);
    lv_obj_set_x(ui_NetPwPanel, 0);
    lv_obj_set_y(ui_NetPwPanel, 195);
    lv_obj_add_flag(ui_NetPwPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_NetPwPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_NetPwPanel, LV_DIR_VER);
    lv_obj_set_style_radius(ui_NetPwPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetPwPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPwPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetPwPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPwPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_NetPwPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_NetPwPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPwPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPwPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPwPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPwPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPwPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPwPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetPwBack = lv_button_create(ui_NetPwPanel);
    lv_obj_set_width(ui_NetPwBack, 116);
    lv_obj_set_height(ui_NetPwBack, 116);
    lv_obj_set_x(ui_NetPwBack, 30);
    lv_obj_set_y(ui_NetPwBack, 50);
    lv_obj_add_flag(ui_NetPwBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_NetPwBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NetPwBack, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetPwBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPwBack, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_NetPwBack, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NetPwBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NetPwBack, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPwBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPwBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPwBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPwBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPwBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPwBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetPwBack, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetPwBack, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_NetPwBack, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetPwBack, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    ui_NetPwBackLabel = lv_label_create(ui_NetPwBack);
    lv_obj_set_width(ui_NetPwBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetPwBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetPwBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetPwBackLabel, "");
    ui_object_set_themeable_style_property(ui_NetPwBackLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetPwBackLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_NetPwBackLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPwBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPwBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPwBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPwBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPwBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPwBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetPwBackLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPwBackLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetPwBackLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPwBackLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_NetPwTitle = lv_label_create(ui_NetPwPanel);
    lv_obj_set_width(ui_NetPwTitle, 480);
    lv_obj_set_height(ui_NetPwTitle, 50);
    lv_obj_set_x(ui_NetPwTitle, 176);
    lv_obj_set_y(ui_NetPwTitle, 85);
    lv_label_set_text(ui_NetPwTitle, "Network");
    ui_object_set_themeable_style_property(ui_NetPwTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_NetPwTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_NetPwTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetPwTitle, &ui_font_MontserratSemiBold44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPwTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPwTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPwTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPwTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPwTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPwTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetPwEyebrow = lv_label_create(ui_NetPwPanel);
    lv_obj_set_width(ui_NetPwEyebrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetPwEyebrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetPwEyebrow, 30);
    lv_obj_set_y(ui_NetPwEyebrow, 187);
    lv_label_set_text(ui_NetPwEyebrow, "PASSWORD");
    ui_object_set_themeable_style_property(ui_NetPwEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_NetPwEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_NetPwEyebrow, &ui_font_MontserratSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPwEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPwEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPwEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPwEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPwEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPwEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetPwBox = lv_obj_create(ui_NetPwPanel);
    lv_obj_set_width(ui_NetPwBox, 660);
    lv_obj_set_height(ui_NetPwBox, 96);
    lv_obj_set_x(ui_NetPwBox, 30);
    lv_obj_set_y(ui_NetPwBox, 227);
    lv_obj_remove_flag(ui_NetPwBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_NetPwBox, LV_DIR_VER);
    lv_obj_set_style_radius(ui_NetPwBox, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetPwBox, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPwBox, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_NetPwBox, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NetPwBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NetPwBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_NetPwBox, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPwBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPwBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPwBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPwBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPwBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPwBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetPwStatus = lv_label_create(ui_NetPwPanel);
    lv_obj_set_width(ui_NetPwStatus, 660);
    lv_obj_set_height(ui_NetPwStatus, 36);
    lv_obj_set_x(ui_NetPwStatus, 30);
    lv_obj_set_y(ui_NetPwStatus, 339);
    lv_label_set_text(ui_NetPwStatus, "Type the password, then OK.");
    ui_object_set_themeable_style_property(ui_NetPwStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_NetPwStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_align(ui_NetPwStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetPwStatus, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPwStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPwStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPwStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPwStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPwStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPwStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetPwKeyboard = lv_obj_create(ui_NetPwPanel);
    lv_obj_set_width(ui_NetPwKeyboard, 720);
    lv_obj_set_height(ui_NetPwKeyboard, 470);
    lv_obj_set_x(ui_NetPwKeyboard, 0);
    lv_obj_set_y(ui_NetPwKeyboard, 451);
    lv_obj_remove_flag(ui_NetPwKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_NetPwKeyboard, LV_DIR_VER);
    lv_obj_set_style_radius(ui_NetPwKeyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_NetPwKeyboard, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPwKeyboard, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_NetPwKeyboard, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_NetPwKeyboard, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_NetPwKeyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_NetPwKeyboard, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetPwKeyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetPwKeyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetPwKeyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetPwKeyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_NetPwKeyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_NetPwKeyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopBar12 = ui_TopBar_create(ui_InternetScreen);
    lv_obj_set_width(ui_TopBar12, 720);
    lv_obj_set_height(ui_TopBar12, 55);
    lv_obj_set_x(ui_TopBar12, 0);
    lv_obj_set_y(ui_TopBar12, 0);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0

    ui_DriveBand12 = ui_DriveBand_create(ui_InternetScreen);
    lv_obj_set_width(ui_DriveBand12, 720);
    lv_obj_set_height(ui_DriveBand12, 140);
    lv_obj_set_x(ui_DriveBand12, 0);
    lv_obj_set_y(ui_DriveBand12, 55);

    ui_ErrorBanner12 = ui_ErrorBanner_create(ui_InternetScreen);
    lv_obj_set_width(ui_ErrorBanner12, 720);
    lv_obj_set_height(ui_ErrorBanner12, 400);
    lv_obj_set_x(ui_ErrorBanner12, 0);
    lv_obj_set_y(ui_ErrorBanner12, 195);

    ui_MenuKey12 = ui_MenuKey_create(ui_InternetScreen);
    lv_obj_set_width(ui_MenuKey12, 720);
    lv_obj_set_height(ui_MenuKey12, 164);
    lv_obj_set_x(ui_MenuKey12, 0);
    lv_obj_set_y(ui_MenuKey12, 1116);

    ui_MenuOverlay12 = ui_MenuOverlay_create(ui_InternetScreen);
    lv_obj_set_width(ui_MenuOverlay12, 720);
    lv_obj_set_height(ui_MenuOverlay12, 921);
    lv_obj_set_x(ui_MenuOverlay12, 0);
    lv_obj_set_y(ui_MenuOverlay12, 195);





}

void ui_InternetScreen_screen_destroy(void)
{
    if(ui_InternetScreen) lv_obj_del(ui_InternetScreen);

    // NULL screen variables
    ui_InternetScreen = NULL;
    ui_InternetBody = NULL;
    ui_InternetTitle = NULL;
    ui_InternetContent = NULL;
    ui_NetConnectionEyebrow = NULL;
    ui_NetChoiceEthernet = NULL;
    ui_NetChoiceEthernetLabel = NULL;
    ui_NetChoiceWifi = NULL;
    ui_NetChoiceWifiLabel = NULL;
    ui_NetWifiEyebrow = NULL;
    ui_NetWifiButton = NULL;
    ui_NetWifiName = NULL;
    ui_NetWifiChevron = NULL;
    ui_NetStatusEyebrow = NULL;
    ui_NetUsingKey = NULL;
    ui_NetUsingValue = NULL;
    ui_NetStateKey = NULL;
    ui_NetStateValue = NULL;
    ui_NetIpKey = NULL;
    ui_NetIpValue = NULL;
    ui_NetSignalKey = NULL;
    ui_NetSignalValue = NULL;
    ui_NetRestartButton = NULL;
    ui_NetRestartButtonLabel = NULL;
    ui_NetPickPanel = NULL;
    ui_NetPickBack = NULL;
    ui_NetPickBackLabel = NULL;
    ui_NetPickTitle = NULL;
    ui_NetPickStatus = NULL;
    ui_NetList = NULL;
    ui_NetRowTemplate = NULL;
    ui_NetPwPanel = NULL;
    ui_NetPwBack = NULL;
    ui_NetPwBackLabel = NULL;
    ui_NetPwTitle = NULL;
    ui_NetPwEyebrow = NULL;
    ui_NetPwBox = NULL;
    ui_NetPwStatus = NULL;
    ui_NetPwKeyboard = NULL;
    ui_TopBar12 = NULL;
    ui_DriveBand12 = NULL;
    ui_ErrorBanner12 = NULL;
    ui_MenuKey12 = NULL;
    ui_MenuOverlay12 = NULL;

}
