// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

lv_obj_t * ui_JoystickScreen = NULL;
lv_obj_t * ui_JoystickBody = NULL;
lv_obj_t * ui_JoystickTitle = NULL;
lv_obj_t * ui_JoystickContent = NULL;
lv_obj_t * ui_JoystickHint = NULL;
lv_obj_t * ui_XAxisEyebrow = NULL;
lv_obj_t * ui_XAxisBar = NULL;
lv_obj_t * ui_YAxisEyebrow = NULL;
lv_obj_t * ui_YAxisBar = NULL;
lv_obj_t * ui_TwistEyebrow = NULL;
lv_obj_t * ui_TwistBar = NULL;
lv_obj_t * ui_ButtonCounterEyebrow = NULL;
lv_obj_t * ui_ButtonCounter = NULL;
lv_obj_t * ui_CalibrateButton = NULL;
lv_obj_t * ui_CalibrateButtonLabel = NULL;
lv_obj_t * ui_CalibrateFill = NULL;
lv_obj_t * ui_TopBar3 = NULL;
lv_obj_t * ui_DriveBand4 = NULL;
lv_obj_t * ui_ErrorBanner10 = NULL;
lv_obj_t * ui_MenuKey3 = NULL;
lv_obj_t * ui_MenuOverlay3 = NULL;
// event funtions

// build funtions

void ui_JoystickScreen_screen_init(void)
{
    ui_JoystickScreen = lv_obj_create(NULL);
    ui_object_set_themeable_style_property(ui_JoystickScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_JoystickScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_JoystickBody = lv_obj_create(ui_JoystickScreen);
    lv_obj_set_width(ui_JoystickBody, 720);
    lv_obj_set_height(ui_JoystickBody, 921);
    lv_obj_set_x(ui_JoystickBody, 0);
    lv_obj_set_y(ui_JoystickBody, 195);
    lv_obj_set_flex_flow(ui_JoystickBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_JoystickBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_JoystickBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_JoystickBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_JoystickBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_JoystickBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_JoystickBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_JoystickBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_JoystickBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_JoystickBody, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_JoystickBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_JoystickBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_JoystickBody, 52, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_JoystickBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_JoystickBody, 34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_JoystickBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JoystickTitle = lv_label_create(ui_JoystickBody);
    lv_obj_set_width(ui_JoystickTitle, 720);
    lv_obj_set_height(ui_JoystickTitle, 47);
    lv_obj_set_x(ui_JoystickTitle, 0);
    lv_obj_set_y(ui_JoystickTitle, -7);
    lv_label_set_text(ui_JoystickTitle, "Joystick test");
    ui_object_set_themeable_style_property(ui_JoystickTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_JoystickTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_JoystickTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_JoystickTitle, &ui_font_MontserratSemiBold44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_JoystickTitle, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_JoystickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_JoystickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_JoystickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_JoystickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_JoystickTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JoystickContent = lv_obj_create(ui_JoystickBody);
    lv_obj_set_width(ui_JoystickContent, 720);
    lv_obj_set_height(ui_JoystickContent, 788);
    lv_obj_remove_flag(ui_JoystickContent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_JoystickContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_JoystickContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_JoystickContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_JoystickContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_JoystickContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_JoystickContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_JoystickContent, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_JoystickContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_JoystickContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_JoystickContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_JoystickContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_JoystickContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_JoystickContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JoystickHint = lv_label_create(ui_JoystickContent);
    lv_obj_set_width(ui_JoystickHint, 660);
    lv_obj_set_height(ui_JoystickHint, 80);
    lv_obj_set_x(ui_JoystickHint, 30);
    lv_obj_set_y(ui_JoystickHint, 8);
    lv_label_set_text(ui_JoystickHint,
                      "Move the joystick. The bars should follow.\nPress and hold Calibrate (or the stick button).");
    ui_object_set_themeable_style_property(ui_JoystickHint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_JoystickHint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_align(ui_JoystickHint, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_JoystickHint, &ui_font_MontserratRegular28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_JoystickHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_JoystickHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_JoystickHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_JoystickHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_JoystickHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_JoystickHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_XAxisEyebrow = lv_label_create(ui_JoystickContent);
    lv_obj_set_width(ui_XAxisEyebrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XAxisEyebrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XAxisEyebrow, 30);
    lv_obj_set_y(ui_XAxisEyebrow, 138);
    lv_label_set_text(ui_XAxisEyebrow, "X");
    ui_object_set_themeable_style_property(ui_XAxisEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_XAxisEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_XAxisEyebrow, &ui_font_MontserratSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_XAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_XAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_XAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_XAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_XAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_XAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_XAxisBar = lv_bar_create(ui_JoystickContent);
    lv_bar_set_value(ui_XAxisBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_XAxisBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_XAxisBar, 660);
    lv_obj_set_height(ui_XAxisBar, 40);
    lv_obj_set_x(ui_XAxisBar, 30);
    lv_obj_set_y(ui_XAxisBar, 176);
    lv_obj_set_style_radius(ui_XAxisBar, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_XAxisBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_XAxisBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_XAxisBar, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_XAxisBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_XAxisBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_XAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_XAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_XAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_XAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_XAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_XAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_XAxisBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_XAxisBar, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_XAxisBar, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_XAxisBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_XAxisBar,
                                                                                               lv_obj_get_style_pad_right(ui_XAxisBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_YAxisEyebrow = lv_label_create(ui_JoystickContent);
    lv_obj_set_width(ui_YAxisEyebrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YAxisEyebrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_YAxisEyebrow, 30);
    lv_obj_set_y(ui_YAxisEyebrow, 278);
    lv_label_set_text(ui_YAxisEyebrow, "Y");
    ui_object_set_themeable_style_property(ui_YAxisEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_YAxisEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_YAxisEyebrow, &ui_font_MontserratSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_YAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_YAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_YAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_YAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_YAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_YAxisEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YAxisBar = lv_bar_create(ui_JoystickContent);
    lv_bar_set_value(ui_YAxisBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_YAxisBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_YAxisBar, 660);
    lv_obj_set_height(ui_YAxisBar, 40);
    lv_obj_set_x(ui_YAxisBar, 30);
    lv_obj_set_y(ui_YAxisBar, 316);
    lv_obj_set_style_radius(ui_YAxisBar, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_YAxisBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_YAxisBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_YAxisBar, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_YAxisBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_YAxisBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_YAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_YAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_YAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_YAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_YAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_YAxisBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_YAxisBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_YAxisBar, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_YAxisBar, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_YAxisBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_YAxisBar,
                                                                                               lv_obj_get_style_pad_right(ui_YAxisBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_TwistEyebrow = lv_label_create(ui_JoystickContent);
    lv_obj_set_width(ui_TwistEyebrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TwistEyebrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TwistEyebrow, 30);
    lv_obj_set_y(ui_TwistEyebrow, 418);
    lv_label_set_text(ui_TwistEyebrow, "TWIST");
    ui_object_set_themeable_style_property(ui_TwistEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_TwistEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_TwistEyebrow, &ui_font_MontserratSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TwistEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TwistEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TwistEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TwistEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TwistEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TwistEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TwistBar = lv_bar_create(ui_JoystickContent);
    lv_bar_set_value(ui_TwistBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TwistBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TwistBar, 660);
    lv_obj_set_height(ui_TwistBar, 40);
    lv_obj_set_x(ui_TwistBar, 30);
    lv_obj_set_y(ui_TwistBar, 456);
    lv_obj_set_style_radius(ui_TwistBar, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TwistBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_TwistBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_TwistBar, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TwistBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TwistBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TwistBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TwistBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TwistBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TwistBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TwistBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TwistBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TwistBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TwistBar, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_TwistBar, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_TwistBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_TwistBar,
                                                                                               lv_obj_get_style_pad_right(ui_TwistBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ButtonCounterEyebrow = lv_label_create(ui_JoystickContent);
    lv_obj_set_width(ui_ButtonCounterEyebrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonCounterEyebrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonCounterEyebrow, 30);
    lv_obj_set_y(ui_ButtonCounterEyebrow, 578);
    lv_label_set_text(ui_ButtonCounterEyebrow, "BUTTON");
    ui_object_set_themeable_style_property(ui_ButtonCounterEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text_muted);
    ui_object_set_themeable_style_property(ui_ButtonCounterEyebrow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text_muted);
    lv_obj_set_style_text_font(ui_ButtonCounterEyebrow, &ui_font_MontserratSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ButtonCounterEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ButtonCounterEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ButtonCounterEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ButtonCounterEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ButtonCounterEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ButtonCounterEyebrow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCounter = lv_label_create(ui_JoystickContent);
    lv_obj_set_width(ui_ButtonCounter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonCounter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonCounter, 30);
    lv_obj_set_y(ui_ButtonCounter, 620);
    lv_label_set_text(ui_ButtonCounter, "0");
    ui_object_set_themeable_style_property(ui_ButtonCounter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_ButtonCounter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_ButtonCounter, &ui_font_IBMPlexSansRegular99, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ButtonCounter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ButtonCounter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ButtonCounter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ButtonCounter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ButtonCounter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ButtonCounter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrateButton = lv_button_create(ui_JoystickContent);
    lv_obj_set_width(ui_CalibrateButton, 360);
    lv_obj_set_height(ui_CalibrateButton, 162);
    lv_obj_set_x(ui_CalibrateButton, 330);
    lv_obj_set_y(ui_CalibrateButton, 572);
    lv_obj_add_flag(ui_CalibrateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CalibrateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalibrateButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CalibrateButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_CalibrateButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_CalibrateButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_CalibrateButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_border_width(ui_CalibrateButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CalibrateButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CalibrateButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CalibrateButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CalibrateButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CalibrateButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CalibrateButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CalibrateButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_CalibrateButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_CalibrateButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_CalibrateButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    ui_CalibrateButtonLabel = lv_label_create(ui_CalibrateButton);
    lv_obj_set_width(ui_CalibrateButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrateButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalibrateButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrateButtonLabel, "Calibrate");
    ui_object_set_themeable_style_property(ui_CalibrateButtonLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_CalibrateButtonLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_font(ui_CalibrateButtonLabel, &ui_font_MontserratSemiBold44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CalibrateButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CalibrateButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CalibrateButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CalibrateButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CalibrateButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CalibrateButtonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CalibrateButtonLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_CalibrateButtonLabel, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_CalibrateButtonLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_CalibrateButtonLabel, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_background);

    ui_CalibrateFill = lv_bar_create(ui_CalibrateButton);
    lv_obj_set_width(ui_CalibrateFill, 328);
    lv_obj_set_height(ui_CalibrateFill, 12);
    lv_obj_set_x(ui_CalibrateFill, 16);
    lv_obj_set_y(ui_CalibrateFill, 134);
    lv_obj_set_style_radius(ui_CalibrateFill, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CalibrateFill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_CalibrateFill, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_color(ui_CalibrateFill, lv_color_hex(0x767676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CalibrateFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CalibrateFill, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CalibrateFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CalibrateFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CalibrateFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CalibrateFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CalibrateFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CalibrateFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CalibrateFill, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_CalibrateFill, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);

    lv_obj_set_style_radius(ui_CalibrateFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CalibrateFill, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_CalibrateFill, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_text);
    ui_object_set_themeable_style_property(ui_CalibrateFill, LV_PART_INDICATOR | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_CalibrateFill, LV_PART_INDICATOR | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_CalibrateFill, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_CalibrateFill,
                                                                                                    lv_obj_get_style_pad_right(ui_CalibrateFill, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_TopBar3 = ui_TopBar_create(ui_JoystickScreen);
    lv_obj_set_width(ui_TopBar3, 720);
    lv_obj_set_height(ui_TopBar3, 55);
    lv_obj_set_x(ui_TopBar3, 0);
    lv_obj_set_y(ui_TopBar3, 0);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0

    ui_DriveBand4 = ui_DriveBand_create(ui_JoystickScreen);
    lv_obj_set_width(ui_DriveBand4, 720);
    lv_obj_set_height(ui_DriveBand4, 140);
    lv_obj_set_x(ui_DriveBand4, 0);
    lv_obj_set_y(ui_DriveBand4, 55);

    ui_ErrorBanner10 = ui_ErrorBanner_create(ui_JoystickScreen);
    lv_obj_set_width(ui_ErrorBanner10, 720);
    lv_obj_set_height(ui_ErrorBanner10, 400);
    lv_obj_set_x(ui_ErrorBanner10, 0);
    lv_obj_set_y(ui_ErrorBanner10, 195);

    ui_MenuKey3 = ui_MenuKey_create(ui_JoystickScreen);
    lv_obj_set_width(ui_MenuKey3, 720);
    lv_obj_set_height(ui_MenuKey3, 164);
    lv_obj_set_x(ui_MenuKey3, 0);
    lv_obj_set_y(ui_MenuKey3, 1116);

    ui_MenuOverlay3 = ui_MenuOverlay_create(ui_JoystickScreen);
    lv_obj_set_width(ui_MenuOverlay3, 720);
    lv_obj_set_height(ui_MenuOverlay3, 921);
    lv_obj_set_x(ui_MenuOverlay3, 0);
    lv_obj_set_y(ui_MenuOverlay3, 195);



}

void ui_JoystickScreen_screen_destroy(void)
{
    if(ui_JoystickScreen) lv_obj_del(ui_JoystickScreen);

    // NULL screen variables
    ui_JoystickScreen = NULL;
    ui_JoystickBody = NULL;
    ui_JoystickTitle = NULL;
    ui_JoystickContent = NULL;
    ui_JoystickHint = NULL;
    ui_XAxisEyebrow = NULL;
    ui_XAxisBar = NULL;
    ui_YAxisEyebrow = NULL;
    ui_YAxisBar = NULL;
    ui_TwistEyebrow = NULL;
    ui_TwistBar = NULL;
    ui_ButtonCounterEyebrow = NULL;
    ui_ButtonCounter = NULL;
    ui_CalibrateButton = NULL;
    ui_CalibrateButtonLabel = NULL;
    ui_CalibrateFill = NULL;
    ui_TopBar3 = NULL;
    ui_DriveBand4 = NULL;
    ui_ErrorBanner10 = NULL;
    ui_MenuKey3 = NULL;
    ui_MenuOverlay3 = NULL;

}
