// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef UI_JOYSTICKSCREEN_H
#define UI_JOYSTICKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_JoystickScreen
extern void ui_JoystickScreen_screen_init(void);
extern void ui_JoystickScreen_screen_destroy(void);
extern lv_obj_t * ui_JoystickScreen;
extern lv_obj_t * ui_JoystickBody;
extern lv_obj_t * ui_JoystickTitle;
extern lv_obj_t * ui_JoystickContent;
extern lv_obj_t * ui_JoystickHint;
extern lv_obj_t * ui_XAxisEyebrow;
extern lv_obj_t * ui_XAxisBar;
extern lv_obj_t * ui_YAxisEyebrow;
extern lv_obj_t * ui_YAxisBar;
extern lv_obj_t * ui_TwistEyebrow;
extern lv_obj_t * ui_TwistBar;
extern lv_obj_t * ui_ButtonCounterEyebrow;
extern lv_obj_t * ui_ButtonCounter;
extern lv_obj_t * ui_CalibrateButton;
extern lv_obj_t * ui_CalibrateButtonLabel;
extern lv_obj_t * ui_TopBar3;
extern lv_obj_t * ui_DriveBand4;
extern lv_obj_t * ui_ErrorBanner10;
extern lv_obj_t * ui_MenuKey3;
extern lv_obj_t * ui_MenuOverlay3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

