// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#include "../ui.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_SettingsBody = NULL;
lv_obj_t * ui_SettingsTitle = NULL;
lv_obj_t * ui_SettingsContent = NULL;
lv_obj_t * ui_SettingsRows = NULL;
lv_obj_t * ui_SpecificSettingsInnerPanel = NULL;
lv_obj_t * ui_SpecificSettingsRows = NULL;
lv_obj_t * ui_Parameter1 = NULL;
lv_obj_t * ui_TopBar8 = NULL;
lv_obj_t * ui_ErrorBanner6 = NULL;
lv_obj_t * ui_DriveBand7 = NULL;
lv_obj_t * ui_MenuKey7 = NULL;
lv_obj_t * ui_MenuOverlay7 = NULL;
// event funtions

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_set_scroll_snap_x(ui_SettingsScreen, LV_SCROLL_SNAP_CENTER);
    ui_object_set_themeable_style_property(ui_SettingsScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SettingsScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_SettingsBody = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_width(ui_SettingsBody, 720);
    lv_obj_set_height(ui_SettingsBody, 921);
    lv_obj_set_x(ui_SettingsBody, 0);
    lv_obj_set_y(ui_SettingsBody, 195);
    lv_obj_set_flex_flow(ui_SettingsBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_SettingsBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SettingsBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SettingsBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SettingsBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SettingsBody, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_SettingsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingsBody, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SettingsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsBody, 52, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsBody, 34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsTitle = lv_label_create(ui_SettingsBody);
    lv_obj_set_width(ui_SettingsTitle, 720);
    lv_obj_set_height(ui_SettingsTitle, 47);
    lv_obj_set_x(ui_SettingsTitle, 0);
    lv_obj_set_y(ui_SettingsTitle, -7);
    lv_label_set_text(ui_SettingsTitle, "UI Settings");
    ui_object_set_themeable_style_property(ui_SettingsTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_text);
    ui_object_set_themeable_style_property(ui_SettingsTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_text);
    lv_obj_set_style_text_align(ui_SettingsTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsTitle, &ui_font_MontserratSemiBold44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SettingsTitle, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsContent = lv_obj_create(ui_SettingsBody);
    lv_obj_set_width(ui_SettingsContent, 720);
    lv_obj_set_height(ui_SettingsContent, 788);
    lv_obj_remove_flag(ui_SettingsContent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SettingsContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SettingsContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SettingsContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SettingsContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_width(ui_SettingsContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingsContent, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SettingsContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsRows = lv_obj_create(ui_SettingsContent);
    lv_obj_set_width(ui_SettingsRows, 720);
    lv_obj_set_height(ui_SettingsRows, 788);
    lv_obj_set_align(ui_SettingsRows, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_SettingsRows, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingsRows, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsRows, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_SettingsRows, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_SettingsRows, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_SettingsRows, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_SettingsRows, LV_SCROLL_SNAP_START);
    ui_object_set_themeable_style_property(ui_SettingsRows, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SettingsRows, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_side(ui_SettingsRows, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpecificSettingsInnerPanel = lv_obj_create(ui_SettingsRows);
    lv_obj_set_width(ui_SpecificSettingsInnerPanel, 720);
    lv_obj_set_height(ui_SpecificSettingsInnerPanel, 790);
    lv_obj_set_align(ui_SpecificSettingsInnerPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_SpecificSettingsInnerPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SpecificSettingsInnerPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_SpecificSettingsInnerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SpecificSettingsInnerPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SpecificSettingsInnerPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    ui_object_set_themeable_style_property(ui_SpecificSettingsInnerPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SpecificSettingsInnerPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_background);
    lv_obj_set_style_pad_row(ui_SpecificSettingsInnerPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SpecificSettingsInnerPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpecificSettingsRows = lv_obj_create(ui_SpecificSettingsInnerPanel);
    lv_obj_set_width(ui_SpecificSettingsRows, 720);
    lv_obj_set_height(ui_SpecificSettingsRows, 900);
    lv_obj_set_x(ui_SpecificSettingsRows, 0);
    lv_obj_set_y(ui_SpecificSettingsRows, -37);
    lv_obj_set_align(ui_SpecificSettingsRows, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_SpecificSettingsRows, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SpecificSettingsRows, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SpecificSettingsRows, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_SpecificSettingsRows, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_SpecificSettingsRows, LV_DIR_VER);
    ui_object_set_themeable_style_property(ui_SpecificSettingsRows, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SpecificSettingsRows, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_border_side(ui_SpecificSettingsRows, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SpecificSettingsRows, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SpecificSettingsRows, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SpecificSettingsRows, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SpecificSettingsRows, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SpecificSettingsRows, 42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SpecificSettingsRows, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_SpecificSettingsRows, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SpecificSettingsRows, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_Parameter1 = ui_SettingRow_create(ui_SpecificSettingsRows);
    lv_obj_set_x(ui_Parameter1, 0);
    lv_obj_set_y(ui_Parameter1, 100);

    ui_TopBar8 = ui_TopBar_create(ui_SettingsScreen);
    lv_obj_set_width(ui_TopBar8, 720);
    lv_obj_set_height(ui_TopBar8, 55);
    lv_obj_set_x(ui_TopBar8, 0);
    lv_obj_set_y(ui_TopBar8, 0);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0

    ui_ErrorBanner6 = ui_ErrorBanner_create(ui_SettingsScreen);
    lv_obj_set_width(ui_ErrorBanner6, 720);
    lv_obj_set_height(ui_ErrorBanner6, 400);
    lv_obj_set_x(ui_ErrorBanner6, 0);
    lv_obj_set_y(ui_ErrorBanner6, 195);

    ui_DriveBand7 = ui_DriveBand_create(ui_SettingsScreen);
    lv_obj_set_width(ui_DriveBand7, 720);
    lv_obj_set_height(ui_DriveBand7, 140);
    lv_obj_set_x(ui_DriveBand7, 0);
    lv_obj_set_y(ui_DriveBand7, 55);

    ui_MenuKey7 = ui_MenuKey_create(ui_SettingsScreen);
    lv_obj_set_width(ui_MenuKey7, 720);
    lv_obj_set_height(ui_MenuKey7, 164);
    lv_obj_set_x(ui_MenuKey7, 0);
    lv_obj_set_y(ui_MenuKey7, 1116);

    ui_MenuOverlay7 = ui_MenuOverlay_create(ui_SettingsScreen);
    lv_obj_set_width(ui_MenuOverlay7, 720);
    lv_obj_set_height(ui_MenuOverlay7, 921);
    lv_obj_set_x(ui_MenuOverlay7, 0);
    lv_obj_set_y(ui_MenuOverlay7, 195);



}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_SettingsBody = NULL;
    ui_SettingsTitle = NULL;
    ui_SettingsContent = NULL;
    ui_SettingsRows = NULL;
    ui_SpecificSettingsInnerPanel = NULL;
    ui_SpecificSettingsRows = NULL;
    ui_Parameter1 = NULL;
    ui_TopBar8 = NULL;
    ui_ErrorBanner6 = NULL;
    ui_DriveBand7 = NULL;
    ui_MenuKey7 = NULL;
    ui_MenuOverlay7 = NULL;

}
