// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef UI_SKUNKWORKSSCREEN_H
#define UI_SKUNKWORKSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SkunkWorksScreen
extern void ui_SkunkWorksScreen_screen_init(void);
extern void ui_SkunkWorksScreen_screen_destroy(void);
extern lv_obj_t * ui_SkunkWorksScreen;
extern lv_obj_t * ui_SkunkWorksBody;
extern lv_obj_t * ui_SkunkWorksTitle;
extern lv_obj_t * ui_SkunkWorksContent;
extern lv_obj_t * ui_SlotRows;
extern lv_obj_t * ui_GenericActionsFlexPanel;
extern lv_obj_t * ui_SlotTile;
extern lv_obj_t * ui_TopBar9;
extern lv_obj_t * ui_ErrorBanner7;
extern lv_obj_t * ui_DriveBand8;
extern lv_obj_t * ui_MenuKey8;
extern lv_obj_t * ui_MenuOverlay8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

