// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef UI_UPDATESCREEN_H
#define UI_UPDATESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_UpdateScreen
extern void ui_UpdateScreen_screen_init(void);
extern void ui_UpdateScreen_screen_destroy(void);
extern lv_obj_t * ui_UpdateScreen;
extern lv_obj_t * ui_UpdateBody;
extern lv_obj_t * ui_UpdateTitle;
extern lv_obj_t * ui_UpdateContent;
extern lv_obj_t * ui_UpdateInstalledEyebrow;
extern lv_obj_t * ui_UpdateInstalled;
extern lv_obj_t * ui_UpdateReleasesEyebrow;
extern lv_obj_t * ui_UpdateStatus;
extern lv_obj_t * ui_UpdateList;
extern lv_obj_t * ui_ReleaseRowTemplate;
extern lv_obj_t * ui_UpdatePickPanel;
extern lv_obj_t * ui_UpdatePickBack;
extern lv_obj_t * ui_UpdatePickBackLabel;
extern lv_obj_t * ui_UpdatePickTitle;
extern lv_obj_t * ui_UpdatePickEyebrow;
extern lv_obj_t * ui_UpdatePickDateKey;
extern lv_obj_t * ui_UpdatePickDateValue;
extern lv_obj_t * ui_UpdatePickKindKey;
extern lv_obj_t * ui_UpdatePickKindValue;
extern lv_obj_t * ui_UpdatePickSizeKey;
extern lv_obj_t * ui_UpdatePickSizeValue;
extern lv_obj_t * ui_UpdateNotesEyebrow;
extern lv_obj_t * ui_UpdateNotesBox;
extern lv_obj_t * ui_UpdatePickNotes;
extern lv_obj_t * ui_UpdatePickStatus;
extern lv_obj_t * ui_UpdateInstallButton;
extern lv_obj_t * ui_UpdateInstallButtonLabel;
extern lv_obj_t * ui_UpdateRunPanel;
extern lv_obj_t * ui_UpdateRunTitle;
extern lv_obj_t * ui_UpdateRunStatus;
extern lv_obj_t * ui_UpdateProgressBar;
extern lv_obj_t * ui_UpdateProgressLabel;
extern lv_obj_t * ui_UpdateLogEyebrow;
extern lv_obj_t * ui_UpdateLogBox;
extern lv_obj_t * ui_UpdateRunLog;
extern lv_obj_t * ui_UpdateRunButton;
extern lv_obj_t * ui_UpdateRunButtonLabel;
extern lv_obj_t * ui_TopBar11;
extern lv_obj_t * ui_ErrorBanner9;
extern lv_obj_t * ui_DriveBand10;
extern lv_obj_t * ui_MenuKey10;
extern lv_obj_t * ui_MenuOverlay10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

