// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: pace-hmi-ui

#ifndef _PACE_HMI_UI_UI_H
#define _PACE_HMI_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"
#include "screens/ui_SettingsScreen.h"
#include "screens/ui_DriveScreen.h"
#include "screens/ui_SVGTestScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1180088808);    // assets/electronics-svgrepo-com.svg
LV_IMG_DECLARE(ui_img_633030620);    // assets/atdev-logo.svg

// FONTS
LV_FONT_DECLARE(ui_font_Digital7);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
